"""add admin notification deliveries

Revision ID: 22a5cd2a04fc
Revises: 29505d4bc0e6
Create Date: 2026-07-12 15:57:14.131604

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22a5cd2a04fc'
down_revision: Union[str, Sequence[str], None] = '29505d4bc0e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_notification_deliveries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=True),
    sa.Column('recipient_user_id', sa.Integer(), nullable=True),
    sa.Column('channel_type', sa.String(length=30), nullable=False),
    sa.Column('destination', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('provider_message_id', sa.String(length=500), nullable=True),
    sa.Column('provider_status_code', sa.Integer(), nullable=True),
    sa.Column('error_type', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('provider_response_json', sa.Text(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('processing_started_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['channel_id'], ['admin_notification_channels.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['notification_id'], ['admin_notifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_notification_deliveries_channel_id'), 'admin_notification_deliveries', ['channel_id'], unique=False)
    op.create_index(op.f('ix_admin_notification_deliveries_channel_type'), 'admin_notification_deliveries', ['channel_type'], unique=False)
    op.create_index(op.f('ix_admin_notification_deliveries_created_at'), 'admin_notification_deliveries', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_notification_deliveries_delivered_at'), 'admin_notification_deliveries', ['delivered_at'], unique=False)
    op.create_index(op.f('ix_admin_notification_deliveries_error_type'), 'admin_notification_deliveries', ['error_type'], unique=False)
    op.create_index(op.f('ix_admin_notification_deliveries_id'), 'admin_notification_deliveries', ['id'], unique=False)
    op.create_index(op.f('ix_admin_notification_deliveries_next_retry_at'), 'admin_notification_deliveries', ['next_retry_at'], unique=False)
    op.create_index(op.f('ix_admin_notification_deliveries_notification_id'), 'admin_notification_deliveries', ['notification_id'], unique=False)
    op.create_index(op.f('ix_admin_notification_deliveries_provider_message_id'), 'admin_notification_deliveries', ['provider_message_id'], unique=False)
    op.create_index(op.f('ix_admin_notification_deliveries_recipient_user_id'), 'admin_notification_deliveries', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_admin_notification_deliveries_scheduled_at'), 'admin_notification_deliveries', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_admin_notification_deliveries_status'), 'admin_notification_deliveries', ['status'], unique=False)
    op.create_index('ix_admin_notification_delivery_notification', 'admin_notification_deliveries', ['notification_id', 'channel_type', 'status'], unique=False)
    op.create_index('ix_admin_notification_delivery_queue', 'admin_notification_deliveries', ['status', 'next_retry_at', 'scheduled_at'], unique=False)
    op.create_index('ix_admin_notification_delivery_recipient', 'admin_notification_deliveries', ['recipient_user_id', 'status', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admin_notification_delivery_recipient', table_name='admin_notification_deliveries')
    op.drop_index('ix_admin_notification_delivery_queue', table_name='admin_notification_deliveries')
    op.drop_index('ix_admin_notification_delivery_notification', table_name='admin_notification_deliveries')
    op.drop_index(op.f('ix_admin_notification_deliveries_status'), table_name='admin_notification_deliveries')
    op.drop_index(op.f('ix_admin_notification_deliveries_scheduled_at'), table_name='admin_notification_deliveries')
    op.drop_index(op.f('ix_admin_notification_deliveries_recipient_user_id'), table_name='admin_notification_deliveries')
    op.drop_index(op.f('ix_admin_notification_deliveries_provider_message_id'), table_name='admin_notification_deliveries')
    op.drop_index(op.f('ix_admin_notification_deliveries_notification_id'), table_name='admin_notification_deliveries')
    op.drop_index(op.f('ix_admin_notification_deliveries_next_retry_at'), table_name='admin_notification_deliveries')
    op.drop_index(op.f('ix_admin_notification_deliveries_id'), table_name='admin_notification_deliveries')
    op.drop_index(op.f('ix_admin_notification_deliveries_error_type'), table_name='admin_notification_deliveries')
    op.drop_index(op.f('ix_admin_notification_deliveries_delivered_at'), table_name='admin_notification_deliveries')
    op.drop_index(op.f('ix_admin_notification_deliveries_created_at'), table_name='admin_notification_deliveries')
    op.drop_index(op.f('ix_admin_notification_deliveries_channel_type'), table_name='admin_notification_deliveries')
    op.drop_index(op.f('ix_admin_notification_deliveries_channel_id'), table_name='admin_notification_deliveries')
    op.drop_table('admin_notification_deliveries')
    # ### end Alembic commands ###
