"""complete account security and admin mfa

Revision ID: 2c9d6b13291d
Revises: 63f37a0bd886
Create Date: 2026-07-13 20:25:47.995042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c9d6b13291d'
down_revision: Union[str, Sequence[str], None] = '63f37a0bd886'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_mfa_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('secret_encrypted', sa.Text(), nullable=False),
    sa.Column('recovery_codes_json', sa.Text(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_mfa_credentials_id'), 'admin_mfa_credentials', ['id'], unique=False)
    op.create_index(op.f('ix_admin_mfa_credentials_is_enabled'), 'admin_mfa_credentials', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_admin_mfa_credentials_user_id'), 'admin_mfa_credentials', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_mfa_credentials_user_id'), table_name='admin_mfa_credentials')
    op.drop_index(op.f('ix_admin_mfa_credentials_is_enabled'), table_name='admin_mfa_credentials')
    op.drop_index(op.f('ix_admin_mfa_credentials_id'), table_name='admin_mfa_credentials')
    op.drop_table('admin_mfa_credentials')
    # ### end Alembic commands ###
