"""add external ai jobs

Revision ID: aeb84b324894
Revises: e568dfcf8111
Create Date: 2026-07-09 15:59:18.113786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aeb84b324894'
down_revision: Union[str, Sequence[str], None] = 'e568dfcf8111'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_ai_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('provider_job_id', sa.String(length=255), nullable=True),
    sa.Column('internal_job_type', sa.String(length=100), nullable=False),
    sa.Column('internal_job_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=100), nullable=False),
    sa.Column('request_json', sa.Text(), nullable=True),
    sa.Column('response_json', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_external_ai_jobs_id'), 'external_ai_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_external_ai_jobs_internal_job_id'), 'external_ai_jobs', ['internal_job_id'], unique=False)
    op.create_index(op.f('ix_external_ai_jobs_internal_job_type'), 'external_ai_jobs', ['internal_job_type'], unique=False)
    op.create_index(op.f('ix_external_ai_jobs_provider'), 'external_ai_jobs', ['provider'], unique=False)
    op.create_index(op.f('ix_external_ai_jobs_provider_job_id'), 'external_ai_jobs', ['provider_job_id'], unique=False)
    op.create_index(op.f('ix_external_ai_jobs_status'), 'external_ai_jobs', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_external_ai_jobs_status'), table_name='external_ai_jobs')
    op.drop_index(op.f('ix_external_ai_jobs_provider_job_id'), table_name='external_ai_jobs')
    op.drop_index(op.f('ix_external_ai_jobs_provider'), table_name='external_ai_jobs')
    op.drop_index(op.f('ix_external_ai_jobs_internal_job_type'), table_name='external_ai_jobs')
    op.drop_index(op.f('ix_external_ai_jobs_internal_job_id'), table_name='external_ai_jobs')
    op.drop_index(op.f('ix_external_ai_jobs_id'), table_name='external_ai_jobs')
    op.drop_table('external_ai_jobs')
    # ### end Alembic commands ###
