"""extend billing coupons

Revision ID: bacec86dc45b
Revises: 957d97d3ee3c
Create Date: 2026-07-10 20:28:24.038559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bacec86dc45b'
down_revision: Union[str, Sequence[str], None] = '957d97d3ee3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_coupons', sa.Column('duration', sa.String(length=30), nullable=False))
    op.add_column('billing_coupons', sa.Column('duration_in_months', sa.Integer(), nullable=True))
    op.add_column('billing_coupons', sa.Column('first_time_transaction_only', sa.Boolean(), nullable=False))
    op.add_column('billing_coupons', sa.Column('minimum_amount', sa.Numeric(precision=12, scale=2), nullable=True))
    op.create_index(op.f('ix_billing_coupons_discount_type'), 'billing_coupons', ['discount_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_billing_coupons_discount_type'), table_name='billing_coupons')
    op.drop_column('billing_coupons', 'minimum_amount')
    op.drop_column('billing_coupons', 'first_time_transaction_only')
    op.drop_column('billing_coupons', 'duration_in_months')
    op.drop_column('billing_coupons', 'duration')
    # ### end Alembic commands ###
