"""add operational events

Revision ID: ca110057b06e
Revises: 2a2cd6382a07
Create Date: 2026-07-12 13:12:06.082053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca110057b06e'
down_revision: Union[str, Sequence[str], None] = '2a2cd6382a07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('operational_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=150), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('background_job_id', sa.Integer(), nullable=True),
    sa.Column('tryon_job_id', sa.Integer(), nullable=True),
    sa.Column('provider_job_id', sa.String(length=255), nullable=True),
    sa.Column('exception_type', sa.String(length=255), nullable=True),
    sa.Column('exception_message', sa.Text(), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_by_user_id', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_operational_events_background_job_id'), 'operational_events', ['background_job_id'], unique=False)
    op.create_index(op.f('ix_operational_events_correlation_id'), 'operational_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_operational_events_created_at'), 'operational_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_operational_events_event_type'), 'operational_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_operational_events_exception_type'), 'operational_events', ['exception_type'], unique=False)
    op.create_index(op.f('ix_operational_events_id'), 'operational_events', ['id'], unique=False)
    op.create_index(op.f('ix_operational_events_is_resolved'), 'operational_events', ['is_resolved'], unique=False)
    op.create_index(op.f('ix_operational_events_provider_job_id'), 'operational_events', ['provider_job_id'], unique=False)
    op.create_index(op.f('ix_operational_events_resolved_by_user_id'), 'operational_events', ['resolved_by_user_id'], unique=False)
    op.create_index(op.f('ix_operational_events_severity'), 'operational_events', ['severity'], unique=False)
    op.create_index(op.f('ix_operational_events_source'), 'operational_events', ['source'], unique=False)
    op.create_index('ix_operational_events_source_severity_created', 'operational_events', ['source', 'severity', 'created_at'], unique=False)
    op.create_index(op.f('ix_operational_events_tryon_job_id'), 'operational_events', ['tryon_job_id'], unique=False)
    op.create_index('ix_operational_events_unresolved', 'operational_events', ['is_resolved', 'severity', 'created_at'], unique=False)
    op.create_index(op.f('ix_operational_events_user_id'), 'operational_events', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_operational_events_user_id'), table_name='operational_events')
    op.drop_index('ix_operational_events_unresolved', table_name='operational_events')
    op.drop_index(op.f('ix_operational_events_tryon_job_id'), table_name='operational_events')
    op.drop_index('ix_operational_events_source_severity_created', table_name='operational_events')
    op.drop_index(op.f('ix_operational_events_source'), table_name='operational_events')
    op.drop_index(op.f('ix_operational_events_severity'), table_name='operational_events')
    op.drop_index(op.f('ix_operational_events_resolved_by_user_id'), table_name='operational_events')
    op.drop_index(op.f('ix_operational_events_provider_job_id'), table_name='operational_events')
    op.drop_index(op.f('ix_operational_events_is_resolved'), table_name='operational_events')
    op.drop_index(op.f('ix_operational_events_id'), table_name='operational_events')
    op.drop_index(op.f('ix_operational_events_exception_type'), table_name='operational_events')
    op.drop_index(op.f('ix_operational_events_event_type'), table_name='operational_events')
    op.drop_index(op.f('ix_operational_events_created_at'), table_name='operational_events')
    op.drop_index(op.f('ix_operational_events_correlation_id'), table_name='operational_events')
    op.drop_index(op.f('ix_operational_events_background_job_id'), table_name='operational_events')
    op.drop_table('operational_events')
    # ### end Alembic commands ###
