"""add versioned legal policies and acceptances"""
from alembic import op
import sqlalchemy as sa
revision="d91a4e13b701";down_revision="c8f5d2b0e321";branch_labels=None;depends_on=None
def upgrade():
 op.create_table("legal_documents",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("document_type",sa.String(80),nullable=False),sa.Column("title",sa.String(255),nullable=False),sa.Column("content",sa.Text(),nullable=False),sa.Column("version",sa.String(40),nullable=False),sa.Column("language",sa.String(10),nullable=False),sa.Column("country_scope",sa.String(500),nullable=False),sa.Column("is_required",sa.Boolean(),nullable=False),sa.Column("is_published",sa.Boolean(),nullable=False),sa.Column("effective_at",sa.DateTime()),sa.Column("published_at",sa.DateTime()),sa.Column("content_hash",sa.String(64),nullable=False),sa.Column("created_by_user_id",sa.Integer()),sa.Column("published_by_user_id",sa.Integer()),sa.Column("created_at",sa.DateTime(),nullable=False),sa.Column("updated_at",sa.DateTime(),nullable=False),sa.UniqueConstraint("document_type","version","language",name="uq_legal_document_version_language"))
 op.create_index("ix_legal_documents_type","legal_documents",["document_type"]);op.create_index("ix_legal_documents_published","legal_documents",["is_published"])
 op.create_table("legal_acceptances",sa.Column("id",sa.Integer(),primary_key=True),sa.Column("user_id",sa.Integer(),sa.ForeignKey("users.id",ondelete="CASCADE"),nullable=False),sa.Column("legal_document_id",sa.Integer(),sa.ForeignKey("legal_documents.id",ondelete="RESTRICT"),nullable=False),sa.Column("document_type",sa.String(80),nullable=False),sa.Column("document_version",sa.String(40),nullable=False),sa.Column("document_hash",sa.String(64),nullable=False),sa.Column("context",sa.String(80),nullable=False),sa.Column("context_reference",sa.String(255),nullable=False),sa.Column("token_purchase_id",sa.Integer(),sa.ForeignKey("token_purchases.id",ondelete="SET NULL")),sa.Column("billing_payment_id",sa.Integer(),sa.ForeignKey("billing_payments.id",ondelete="SET NULL")),sa.Column("token_bag_id",sa.Integer(),sa.ForeignKey("token_value_lots.id",ondelete="SET NULL")),sa.Column("ip_address",sa.String(64)),sa.Column("country_code",sa.String(8)),sa.Column("language",sa.String(10)),sa.Column("user_agent",sa.Text()),sa.Column("accepted_at",sa.DateTime(),nullable=False),sa.UniqueConstraint("user_id","legal_document_id","context","context_reference",name="uq_legal_acceptance_context"))
 for c in ("user_id","legal_document_id","context","context_reference","token_purchase_id","billing_payment_id","token_bag_id"):op.create_index(f"ix_legal_acceptances_{c}","legal_acceptances",[c])
def downgrade():op.drop_table("legal_acceptances");op.drop_table("legal_documents")
