"""add rate limiting and anti abuse models

Revision ID: dd65f6073acb
Revises: bacec86dc45b
Create Date: 2026-07-11 11:37:50.829257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd65f6073acb'
down_revision: Union[str, Sequence[str], None] = 'bacec86dc45b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_policies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('route_pattern', sa.String(length=500), nullable=False),
    sa.Column('http_method', sa.String(length=20), nullable=True),
    sa.Column('scope', sa.String(length=50), nullable=False),
    sa.Column('algorithm', sa.String(length=50), nullable=False),
    sa.Column('request_limit', sa.Integer(), nullable=False),
    sa.Column('window_seconds', sa.Integer(), nullable=False),
    sa.Column('burst_limit', sa.Integer(), nullable=True),
    sa.Column('block_seconds', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('applies_to_authenticated', sa.Boolean(), nullable=False),
    sa.Column('applies_to_anonymous', sa.Boolean(), nullable=False),
    sa.Column('include_headers', sa.Boolean(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limit_policies_http_method'), 'rate_limit_policies', ['http_method'], unique=False)
    op.create_index(op.f('ix_rate_limit_policies_id'), 'rate_limit_policies', ['id'], unique=False)
    op.create_index(op.f('ix_rate_limit_policies_is_enabled'), 'rate_limit_policies', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_rate_limit_policies_key'), 'rate_limit_policies', ['key'], unique=True)
    op.create_index(op.f('ix_rate_limit_policies_priority'), 'rate_limit_policies', ['priority'], unique=False)
    op.create_index(op.f('ix_rate_limit_policies_route_pattern'), 'rate_limit_policies', ['route_pattern'], unique=False)
    op.create_index(op.f('ix_rate_limit_policies_scope'), 'rate_limit_policies', ['scope'], unique=False)
    op.create_table('abuse_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('rate_limit_policy_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('route', sa.String(length=500), nullable=True),
    sa.Column('http_method', sa.String(length=20), nullable=True),
    sa.Column('identifier', sa.String(length=500), nullable=True),
    sa.Column('request_count', sa.Integer(), nullable=True),
    sa.Column('request_limit', sa.Integer(), nullable=True),
    sa.Column('window_seconds', sa.Integer(), nullable=True),
    sa.Column('blocked_until', sa.DateTime(), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['rate_limit_policy_id'], ['rate_limit_policies.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_abuse_events_api_key_id'), 'abuse_events', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_abuse_events_blocked_until'), 'abuse_events', ['blocked_until'], unique=False)
    op.create_index(op.f('ix_abuse_events_created_at'), 'abuse_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_abuse_events_event_type'), 'abuse_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_abuse_events_id'), 'abuse_events', ['id'], unique=False)
    op.create_index(op.f('ix_abuse_events_identifier'), 'abuse_events', ['identifier'], unique=False)
    op.create_index(op.f('ix_abuse_events_ip_address'), 'abuse_events', ['ip_address'], unique=False)
    op.create_index(op.f('ix_abuse_events_rate_limit_policy_id'), 'abuse_events', ['rate_limit_policy_id'], unique=False)
    op.create_index(op.f('ix_abuse_events_route'), 'abuse_events', ['route'], unique=False)
    op.create_index(op.f('ix_abuse_events_severity'), 'abuse_events', ['severity'], unique=False)
    op.create_index(op.f('ix_abuse_events_status'), 'abuse_events', ['status'], unique=False)
    op.create_index(op.f('ix_abuse_events_user_id'), 'abuse_events', ['user_id'], unique=False)
    op.create_table('security_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=False),
    sa.Column('target_value', sa.String(length=500), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('abuse_event_id', sa.Integer(), nullable=True),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('is_permanent', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['abuse_event_id'], ['abuse_events.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_security_blocks_abuse_event_id'), 'security_blocks', ['abuse_event_id'], unique=False)
    op.create_index(op.f('ix_security_blocks_expires_at'), 'security_blocks', ['expires_at'], unique=False)
    op.create_index(op.f('ix_security_blocks_id'), 'security_blocks', ['id'], unique=False)
    op.create_index(op.f('ix_security_blocks_is_active'), 'security_blocks', ['is_active'], unique=False)
    op.create_index(op.f('ix_security_blocks_target_type'), 'security_blocks', ['target_type'], unique=False)
    op.create_index(op.f('ix_security_blocks_target_value'), 'security_blocks', ['target_value'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_security_blocks_target_value'), table_name='security_blocks')
    op.drop_index(op.f('ix_security_blocks_target_type'), table_name='security_blocks')
    op.drop_index(op.f('ix_security_blocks_is_active'), table_name='security_blocks')
    op.drop_index(op.f('ix_security_blocks_id'), table_name='security_blocks')
    op.drop_index(op.f('ix_security_blocks_expires_at'), table_name='security_blocks')
    op.drop_index(op.f('ix_security_blocks_abuse_event_id'), table_name='security_blocks')
    op.drop_table('security_blocks')
    op.drop_index(op.f('ix_abuse_events_user_id'), table_name='abuse_events')
    op.drop_index(op.f('ix_abuse_events_status'), table_name='abuse_events')
    op.drop_index(op.f('ix_abuse_events_severity'), table_name='abuse_events')
    op.drop_index(op.f('ix_abuse_events_route'), table_name='abuse_events')
    op.drop_index(op.f('ix_abuse_events_rate_limit_policy_id'), table_name='abuse_events')
    op.drop_index(op.f('ix_abuse_events_ip_address'), table_name='abuse_events')
    op.drop_index(op.f('ix_abuse_events_identifier'), table_name='abuse_events')
    op.drop_index(op.f('ix_abuse_events_id'), table_name='abuse_events')
    op.drop_index(op.f('ix_abuse_events_event_type'), table_name='abuse_events')
    op.drop_index(op.f('ix_abuse_events_created_at'), table_name='abuse_events')
    op.drop_index(op.f('ix_abuse_events_blocked_until'), table_name='abuse_events')
    op.drop_index(op.f('ix_abuse_events_api_key_id'), table_name='abuse_events')
    op.drop_table('abuse_events')
    op.drop_index(op.f('ix_rate_limit_policies_scope'), table_name='rate_limit_policies')
    op.drop_index(op.f('ix_rate_limit_policies_route_pattern'), table_name='rate_limit_policies')
    op.drop_index(op.f('ix_rate_limit_policies_priority'), table_name='rate_limit_policies')
    op.drop_index(op.f('ix_rate_limit_policies_key'), table_name='rate_limit_policies')
    op.drop_index(op.f('ix_rate_limit_policies_is_enabled'), table_name='rate_limit_policies')
    op.drop_index(op.f('ix_rate_limit_policies_id'), table_name='rate_limit_policies')
    op.drop_index(op.f('ix_rate_limit_policies_http_method'), table_name='rate_limit_policies')
    op.drop_table('rate_limit_policies')
    # ### end Alembic commands ###
