"""add admin notification center

Revision ID: e71c82653cf2
Revises: 6a324dc7ae78
Create Date: 2026-07-12 15:16:26.809008

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e71c82653cf2'
down_revision: Union[str, Sequence[str], None] = '6a324dc7ae78'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('event_type', sa.String(length=150), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('action_url', sa.String(length=2000), nullable=True),
    sa.Column('action_label', sa.String(length=120), nullable=True),
    sa.Column('entity_type', sa.String(length=120), nullable=True),
    sa.Column('entity_id', sa.String(length=150), nullable=True),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('requires_action', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_notifications_correlation_id'), 'admin_notifications', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_admin_notifications_created_at'), 'admin_notifications', ['created_at'], unique=False)
    op.create_index('ix_admin_notifications_entity', 'admin_notifications', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_admin_notifications_entity_id'), 'admin_notifications', ['entity_id'], unique=False)
    op.create_index(op.f('ix_admin_notifications_entity_type'), 'admin_notifications', ['entity_type'], unique=False)
    op.create_index(op.f('ix_admin_notifications_event_type'), 'admin_notifications', ['event_type'], unique=False)
    op.create_index(op.f('ix_admin_notifications_expires_at'), 'admin_notifications', ['expires_at'], unique=False)
    op.create_index('ix_admin_notifications_global_status', 'admin_notifications', ['is_global', 'is_read', 'is_archived', 'created_at'], unique=False)
    op.create_index(op.f('ix_admin_notifications_id'), 'admin_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_admin_notifications_is_archived'), 'admin_notifications', ['is_archived'], unique=False)
    op.create_index(op.f('ix_admin_notifications_is_global'), 'admin_notifications', ['is_global'], unique=False)
    op.create_index(op.f('ix_admin_notifications_is_read'), 'admin_notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_admin_notifications_notification_type'), 'admin_notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_admin_notifications_priority'), 'admin_notifications', ['priority'], unique=False)
    op.create_index('ix_admin_notifications_recipient_status', 'admin_notifications', ['recipient_user_id', 'is_read', 'is_archived', 'created_at'], unique=False)
    op.create_index(op.f('ix_admin_notifications_recipient_user_id'), 'admin_notifications', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_admin_notifications_requires_action'), 'admin_notifications', ['requires_action'], unique=False)
    op.create_index(op.f('ix_admin_notifications_source'), 'admin_notifications', ['source'], unique=False)
    op.create_index('ix_admin_notifications_source_priority', 'admin_notifications', ['source', 'priority', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admin_notifications_source_priority', table_name='admin_notifications')
    op.drop_index(op.f('ix_admin_notifications_source'), table_name='admin_notifications')
    op.drop_index(op.f('ix_admin_notifications_requires_action'), table_name='admin_notifications')
    op.drop_index(op.f('ix_admin_notifications_recipient_user_id'), table_name='admin_notifications')
    op.drop_index('ix_admin_notifications_recipient_status', table_name='admin_notifications')
    op.drop_index(op.f('ix_admin_notifications_priority'), table_name='admin_notifications')
    op.drop_index(op.f('ix_admin_notifications_notification_type'), table_name='admin_notifications')
    op.drop_index(op.f('ix_admin_notifications_is_read'), table_name='admin_notifications')
    op.drop_index(op.f('ix_admin_notifications_is_global'), table_name='admin_notifications')
    op.drop_index(op.f('ix_admin_notifications_is_archived'), table_name='admin_notifications')
    op.drop_index(op.f('ix_admin_notifications_id'), table_name='admin_notifications')
    op.drop_index('ix_admin_notifications_global_status', table_name='admin_notifications')
    op.drop_index(op.f('ix_admin_notifications_expires_at'), table_name='admin_notifications')
    op.drop_index(op.f('ix_admin_notifications_event_type'), table_name='admin_notifications')
    op.drop_index(op.f('ix_admin_notifications_entity_type'), table_name='admin_notifications')
    op.drop_index(op.f('ix_admin_notifications_entity_id'), table_name='admin_notifications')
    op.drop_index('ix_admin_notifications_entity', table_name='admin_notifications')
    op.drop_index(op.f('ix_admin_notifications_created_at'), table_name='admin_notifications')
    op.drop_index(op.f('ix_admin_notifications_correlation_id'), table_name='admin_notifications')
    op.drop_table('admin_notifications')
    # ### end Alembic commands ###
