"""upgrade system settings engine

Revision ID: fe55a90c6a34
Revises: fca4d42f55f0
Create Date: 2026-07-08 22:19:34.861432

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe55a90c6a34'
down_revision: Union[str, Sequence[str], None] = 'fca4d42f55f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('category', sa.String(length=100), nullable=False))
    op.add_column('system_settings', sa.Column('label', sa.String(length=255), nullable=False))
    op.add_column('system_settings', sa.Column('value_type', sa.String(length=50), nullable=False))
    op.add_column('system_settings', sa.Column('value_string', sa.Text(), nullable=True))
    op.add_column('system_settings', sa.Column('value_integer', sa.Integer(), nullable=True))
    op.add_column('system_settings', sa.Column('value_float', sa.Float(), nullable=True))
    op.add_column('system_settings', sa.Column('value_boolean', sa.Boolean(), nullable=True))
    op.add_column('system_settings', sa.Column('value_json', sa.Text(), nullable=True))
    op.add_column('system_settings', sa.Column('default_value_string', sa.Text(), nullable=True))
    op.add_column('system_settings', sa.Column('default_value_integer', sa.Integer(), nullable=True))
    op.add_column('system_settings', sa.Column('default_value_float', sa.Float(), nullable=True))
    op.add_column('system_settings', sa.Column('default_value_boolean', sa.Boolean(), nullable=True))
    op.add_column('system_settings', sa.Column('default_value_json', sa.Text(), nullable=True))
    op.add_column('system_settings', sa.Column('is_editable', sa.Boolean(), nullable=False))
    op.add_column('system_settings', sa.Column('is_sensitive', sa.Boolean(), nullable=False))
    op.add_column('system_settings', sa.Column('requires_restart', sa.Boolean(), nullable=False))
    op.add_column('system_settings', sa.Column('sort_order', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_system_settings_category'), 'system_settings', ['category'], unique=False)
    op.create_index(op.f('ix_system_settings_value_type'), 'system_settings', ['value_type'], unique=False)
    op.drop_column('system_settings', 'value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_settings', sa.Column('value', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_system_settings_value_type'), table_name='system_settings')
    op.drop_index(op.f('ix_system_settings_category'), table_name='system_settings')
    op.drop_column('system_settings', 'sort_order')
    op.drop_column('system_settings', 'requires_restart')
    op.drop_column('system_settings', 'is_sensitive')
    op.drop_column('system_settings', 'is_editable')
    op.drop_column('system_settings', 'default_value_json')
    op.drop_column('system_settings', 'default_value_boolean')
    op.drop_column('system_settings', 'default_value_float')
    op.drop_column('system_settings', 'default_value_integer')
    op.drop_column('system_settings', 'default_value_string')
    op.drop_column('system_settings', 'value_json')
    op.drop_column('system_settings', 'value_boolean')
    op.drop_column('system_settings', 'value_float')
    op.drop_column('system_settings', 'value_integer')
    op.drop_column('system_settings', 'value_string')
    op.drop_column('system_settings', 'value_type')
    op.drop_column('system_settings', 'label')
    op.drop_column('system_settings', 'category')
    # ### end Alembic commands ###
