"""create tryon and storage tables

Revision ID: 033c77dda0bb
Revises: cc8486a205d7
Create Date: 2026-07-08 18:20:20.662367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '033c77dda0bb'
down_revision: Union[str, Sequence[str], None] = 'cc8486a205d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('bucket', sa.String(length=255), nullable=True),
    sa.Column('object_key', sa.String(length=1000), nullable=False),
    sa.Column('public_url', sa.String(length=1000), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('content_type', sa.String(length=255), nullable=True),
    sa.Column('size_bytes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_storage_files_id'), 'storage_files', ['id'], unique=False)
    op.create_index(op.f('ix_storage_files_provider'), 'storage_files', ['provider'], unique=False)
    op.create_index(op.f('ix_storage_files_user_id'), 'storage_files', ['user_id'], unique=False)
    op.create_table('tryon_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('person_image_file_id', sa.Integer(), nullable=False),
    sa.Column('item_image_file_id', sa.Integer(), nullable=False),
    sa.Column('result_file_id', sa.Integer(), nullable=True),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('tokens_cost', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('runpod_job_id', sa.String(length=255), nullable=True),
    sa.Column('comfy_workflow_name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['item_image_file_id'], ['storage_files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['person_image_file_id'], ['storage_files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['result_file_id'], ['storage_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tryon_jobs_id'), 'tryon_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_tryon_jobs_item_type'), 'tryon_jobs', ['item_type'], unique=False)
    op.create_index(op.f('ix_tryon_jobs_runpod_job_id'), 'tryon_jobs', ['runpod_job_id'], unique=False)
    op.create_index(op.f('ix_tryon_jobs_status'), 'tryon_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_tryon_jobs_user_id'), 'tryon_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tryon_jobs_user_id'), table_name='tryon_jobs')
    op.drop_index(op.f('ix_tryon_jobs_status'), table_name='tryon_jobs')
    op.drop_index(op.f('ix_tryon_jobs_runpod_job_id'), table_name='tryon_jobs')
    op.drop_index(op.f('ix_tryon_jobs_item_type'), table_name='tryon_jobs')
    op.drop_index(op.f('ix_tryon_jobs_id'), table_name='tryon_jobs')
    op.drop_table('tryon_jobs')
    op.drop_index(op.f('ix_storage_files_user_id'), table_name='storage_files')
    op.drop_index(op.f('ix_storage_files_provider'), table_name='storage_files')
    op.drop_index(op.f('ix_storage_files_id'), table_name='storage_files')
    op.drop_table('storage_files')
    # ### end Alembic commands ###
