"""add admin notification preferences and channels

Revision ID: 29505d4bc0e6
Revises: e71c82653cf2
Create Date: 2026-07-12 15:28:09.755571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29505d4bc0e6'
down_revision: Union[str, Sequence[str], None] = 'e71c82653cf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_notification_channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel_type', sa.String(length=30), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('destination', sa.String(length=2000), nullable=True),
    sa.Column('display_name', sa.String(length=150), nullable=True),
    sa.Column('integration_provider', sa.String(length=100), nullable=True),
    sa.Column('configuration_json', sa.Text(), nullable=True),
    sa.Column('minimum_priority', sa.String(length=30), nullable=False),
    sa.Column('send_success_notifications', sa.Boolean(), nullable=False),
    sa.Column('send_info_notifications', sa.Boolean(), nullable=False),
    sa.Column('send_warning_notifications', sa.Boolean(), nullable=False),
    sa.Column('send_error_notifications', sa.Boolean(), nullable=False),
    sa.Column('send_critical_notifications', sa.Boolean(), nullable=False),
    sa.Column('last_tested_at', sa.DateTime(), nullable=True),
    sa.Column('last_test_success', sa.Boolean(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'channel_type', name='uq_admin_notification_channel_user_type')
    )
    op.create_index(op.f('ix_admin_notification_channels_channel_type'), 'admin_notification_channels', ['channel_type'], unique=False)
    op.create_index(op.f('ix_admin_notification_channels_created_at'), 'admin_notification_channels', ['created_at'], unique=False)
    op.create_index('ix_admin_notification_channels_delivery', 'admin_notification_channels', ['channel_type', 'is_enabled', 'status'], unique=False)
    op.create_index(op.f('ix_admin_notification_channels_id'), 'admin_notification_channels', ['id'], unique=False)
    op.create_index(op.f('ix_admin_notification_channels_integration_provider'), 'admin_notification_channels', ['integration_provider'], unique=False)
    op.create_index(op.f('ix_admin_notification_channels_is_enabled'), 'admin_notification_channels', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_admin_notification_channels_minimum_priority'), 'admin_notification_channels', ['minimum_priority'], unique=False)
    op.create_index(op.f('ix_admin_notification_channels_status'), 'admin_notification_channels', ['status'], unique=False)
    op.create_index(op.f('ix_admin_notification_channels_user_id'), 'admin_notification_channels', ['user_id'], unique=False)
    op.create_table('admin_notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('minimum_priority', sa.String(length=30), nullable=False),
    sa.Column('digest_mode', sa.String(length=30), nullable=False),
    sa.Column('enabled_sources_json', sa.Text(), nullable=True),
    sa.Column('enabled_types_json', sa.Text(), nullable=True),
    sa.Column('quiet_hours_enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('allow_urgent_during_quiet_hours', sa.Boolean(), nullable=False),
    sa.Column('allow_critical_during_quiet_hours', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_admin_notification_preferences_user')
    )
    op.create_index(op.f('ix_admin_notification_preferences_created_at'), 'admin_notification_preferences', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_notification_preferences_digest_mode'), 'admin_notification_preferences', ['digest_mode'], unique=False)
    op.create_index(op.f('ix_admin_notification_preferences_id'), 'admin_notification_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_admin_notification_preferences_is_enabled'), 'admin_notification_preferences', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_admin_notification_preferences_minimum_priority'), 'admin_notification_preferences', ['minimum_priority'], unique=False)
    op.create_index(op.f('ix_admin_notification_preferences_quiet_hours_enabled'), 'admin_notification_preferences', ['quiet_hours_enabled'], unique=False)
    op.create_index('ix_admin_notification_preferences_status', 'admin_notification_preferences', ['is_enabled', 'minimum_priority', 'digest_mode'], unique=False)
    op.create_index(op.f('ix_admin_notification_preferences_user_id'), 'admin_notification_preferences', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_notification_preferences_user_id'), table_name='admin_notification_preferences')
    op.drop_index('ix_admin_notification_preferences_status', table_name='admin_notification_preferences')
    op.drop_index(op.f('ix_admin_notification_preferences_quiet_hours_enabled'), table_name='admin_notification_preferences')
    op.drop_index(op.f('ix_admin_notification_preferences_minimum_priority'), table_name='admin_notification_preferences')
    op.drop_index(op.f('ix_admin_notification_preferences_is_enabled'), table_name='admin_notification_preferences')
    op.drop_index(op.f('ix_admin_notification_preferences_id'), table_name='admin_notification_preferences')
    op.drop_index(op.f('ix_admin_notification_preferences_digest_mode'), table_name='admin_notification_preferences')
    op.drop_index(op.f('ix_admin_notification_preferences_created_at'), table_name='admin_notification_preferences')
    op.drop_table('admin_notification_preferences')
    op.drop_index(op.f('ix_admin_notification_channels_user_id'), table_name='admin_notification_channels')
    op.drop_index(op.f('ix_admin_notification_channels_status'), table_name='admin_notification_channels')
    op.drop_index(op.f('ix_admin_notification_channels_minimum_priority'), table_name='admin_notification_channels')
    op.drop_index(op.f('ix_admin_notification_channels_is_enabled'), table_name='admin_notification_channels')
    op.drop_index(op.f('ix_admin_notification_channels_integration_provider'), table_name='admin_notification_channels')
    op.drop_index(op.f('ix_admin_notification_channels_id'), table_name='admin_notification_channels')
    op.drop_index('ix_admin_notification_channels_delivery', table_name='admin_notification_channels')
    op.drop_index(op.f('ix_admin_notification_channels_created_at'), table_name='admin_notification_channels')
    op.drop_index(op.f('ix_admin_notification_channels_channel_type'), table_name='admin_notification_channels')
    op.drop_table('admin_notification_channels')
    # ### end Alembic commands ###
