"""add workflow definitions

Revision ID: 2a2cd6382a07
Revises: f9b3c5c6f9a2
Create Date: 2026-07-11 15:58:58.823905

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a2cd6382a07'
down_revision: Union[str, Sequence[str], None] = 'f9b3c5c6f9a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workflow_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=150), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=False),
    sa.Column('workflow_json', sa.Text(), nullable=False),
    sa.Column('parameter_schema_json', sa.Text(), nullable=True),
    sa.Column('execution_modes_json', sa.Text(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_definitions_category'), 'workflow_definitions', ['category'], unique=False)
    op.create_index('ix_workflow_definitions_category_default', 'workflow_definitions', ['category', 'is_default', 'is_active'], unique=False)
    op.create_index(op.f('ix_workflow_definitions_created_at'), 'workflow_definitions', ['created_at'], unique=False)
    op.create_index(op.f('ix_workflow_definitions_created_by_user_id'), 'workflow_definitions', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_workflow_definitions_id'), 'workflow_definitions', ['id'], unique=False)
    op.create_index(op.f('ix_workflow_definitions_is_active'), 'workflow_definitions', ['is_active'], unique=False)
    op.create_index(op.f('ix_workflow_definitions_is_default'), 'workflow_definitions', ['is_default'], unique=False)
    op.create_index(op.f('ix_workflow_definitions_key'), 'workflow_definitions', ['key'], unique=False)
    op.create_index('ix_workflow_definitions_key_version', 'workflow_definitions', ['key', 'version'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_workflow_definitions_key_version', table_name='workflow_definitions')
    op.drop_index(op.f('ix_workflow_definitions_key'), table_name='workflow_definitions')
    op.drop_index(op.f('ix_workflow_definitions_is_default'), table_name='workflow_definitions')
    op.drop_index(op.f('ix_workflow_definitions_is_active'), table_name='workflow_definitions')
    op.drop_index(op.f('ix_workflow_definitions_id'), table_name='workflow_definitions')
    op.drop_index(op.f('ix_workflow_definitions_created_by_user_id'), table_name='workflow_definitions')
    op.drop_index(op.f('ix_workflow_definitions_created_at'), table_name='workflow_definitions')
    op.drop_index('ix_workflow_definitions_category_default', table_name='workflow_definitions')
    op.drop_index(op.f('ix_workflow_definitions_category'), table_name='workflow_definitions')
    op.drop_table('workflow_definitions')
    # ### end Alembic commands ###
