"""add dynamic pricing and runpod config

Revision ID: 2ef943c646f0
Revises: 033c77dda0bb
Create Date: 2026-07-08 19:39:43.589514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ef943c646f0'
down_revision: Union[str, Sequence[str], None] = '033c77dda0bb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pricing_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False),
    sa.Column('item_type', sa.String(length=50), nullable=False),
    sa.Column('quality_mode', sa.String(length=50), nullable=False),
    sa.Column('tokens_cost', sa.Integer(), nullable=False),
    sa.Column('estimated_gpu_seconds', sa.Integer(), nullable=False),
    sa.Column('estimated_gpu_cost_cents', sa.Integer(), nullable=False),
    sa.Column('margin_percent', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_rules_id'), 'pricing_rules', ['id'], unique=False)
    op.create_index(op.f('ix_pricing_rules_is_active'), 'pricing_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_pricing_rules_item_type'), 'pricing_rules', ['item_type'], unique=False)
    op.create_index(op.f('ix_pricing_rules_operation_type'), 'pricing_rules', ['operation_type'], unique=False)
    op.create_index(op.f('ix_pricing_rules_quality_mode'), 'pricing_rules', ['quality_mode'], unique=False)
    op.create_table('runpod_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('mode', sa.String(length=50), nullable=False),
    sa.Column('endpoint_id', sa.String(length=255), nullable=True),
    sa.Column('endpoint_url', sa.String(length=1000), nullable=True),
    sa.Column('gpu_type', sa.String(length=255), nullable=True),
    sa.Column('docker_image', sa.String(length=500), nullable=True),
    sa.Column('comfy_workflow_name', sa.String(length=255), nullable=True),
    sa.Column('min_workers', sa.Integer(), nullable=False),
    sa.Column('max_workers', sa.Integer(), nullable=False),
    sa.Column('estimated_cost_per_second_cents', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runpod_configs_id'), 'runpod_configs', ['id'], unique=False)
    op.create_index(op.f('ix_runpod_configs_is_active'), 'runpod_configs', ['is_active'], unique=False)
    op.add_column('tryon_jobs', sa.Column('pricing_rule_id', sa.Integer(), nullable=True))
    op.add_column('tryon_jobs', sa.Column('runpod_config_id', sa.Integer(), nullable=True))
    op.add_column('tryon_jobs', sa.Column('quality_mode', sa.String(length=50), nullable=False))
    op.add_column('tryon_jobs', sa.Column('estimated_gpu_seconds', sa.Integer(), nullable=True))
    op.add_column('tryon_jobs', sa.Column('estimated_gpu_cost_cents', sa.Integer(), nullable=True))
    op.add_column('tryon_jobs', sa.Column('actual_gpu_seconds', sa.Integer(), nullable=True))
    op.add_column('tryon_jobs', sa.Column('actual_gpu_cost_cents', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tryon_jobs_pricing_rule_id'), 'tryon_jobs', ['pricing_rule_id'], unique=False)
    op.create_index(op.f('ix_tryon_jobs_quality_mode'), 'tryon_jobs', ['quality_mode'], unique=False)
    op.create_index(op.f('ix_tryon_jobs_runpod_config_id'), 'tryon_jobs', ['runpod_config_id'], unique=False)
    op.create_foreign_key(None, 'tryon_jobs', 'pricing_rules', ['pricing_rule_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tryon_jobs', 'runpod_configs', ['runpod_config_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tryon_jobs', type_='foreignkey')
    op.drop_constraint(None, 'tryon_jobs', type_='foreignkey')
    op.drop_index(op.f('ix_tryon_jobs_runpod_config_id'), table_name='tryon_jobs')
    op.drop_index(op.f('ix_tryon_jobs_quality_mode'), table_name='tryon_jobs')
    op.drop_index(op.f('ix_tryon_jobs_pricing_rule_id'), table_name='tryon_jobs')
    op.drop_column('tryon_jobs', 'actual_gpu_cost_cents')
    op.drop_column('tryon_jobs', 'actual_gpu_seconds')
    op.drop_column('tryon_jobs', 'estimated_gpu_cost_cents')
    op.drop_column('tryon_jobs', 'estimated_gpu_seconds')
    op.drop_column('tryon_jobs', 'quality_mode')
    op.drop_column('tryon_jobs', 'runpod_config_id')
    op.drop_column('tryon_jobs', 'pricing_rule_id')
    op.drop_index(op.f('ix_runpod_configs_is_active'), table_name='runpod_configs')
    op.drop_index(op.f('ix_runpod_configs_id'), table_name='runpod_configs')
    op.drop_table('runpod_configs')
    op.drop_index(op.f('ix_pricing_rules_quality_mode'), table_name='pricing_rules')
    op.drop_index(op.f('ix_pricing_rules_operation_type'), table_name='pricing_rules')
    op.drop_index(op.f('ix_pricing_rules_item_type'), table_name='pricing_rules')
    op.drop_index(op.f('ix_pricing_rules_is_active'), table_name='pricing_rules')
    op.drop_index(op.f('ix_pricing_rules_id'), table_name='pricing_rules')
    op.drop_table('pricing_rules')
    # ### end Alembic commands ###
