"""add i18n locales translations and user preferences

Revision ID: 310b99237764
Revises: 8f30b664416e
Create Date: 2026-07-13 10:35:01.021117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '310b99237764'
down_revision: Union[str, Sequence[str], None] = '8f30b664416e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('i18n_locales',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('native_name', sa.String(length=150), nullable=False),
    sa.Column('fallback_locale_code', sa.String(length=20), nullable=True),
    sa.Column('currency_code', sa.String(length=10), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('date_format', sa.String(length=50), nullable=False),
    sa.Column('time_format', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_index('ix_i18n_locales_active_default', 'i18n_locales', ['is_active', 'is_default'], unique=False)
    op.create_index(op.f('ix_i18n_locales_fallback_locale_code'), 'i18n_locales', ['fallback_locale_code'], unique=False)
    op.create_index(op.f('ix_i18n_locales_is_active'), 'i18n_locales', ['is_active'], unique=False)
    op.create_index(op.f('ix_i18n_locales_is_default'), 'i18n_locales', ['is_default'], unique=False)
    op.create_table('i18n_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('locale_code', sa.String(length=20), nullable=False),
    sa.Column('namespace', sa.String(length=100), nullable=False),
    sa.Column('translation_key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_html', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['locale_code'], ['i18n_locales.code'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('locale_code', 'translation_key', name='uq_i18n_translation_locale_key')
    )
    op.create_index(op.f('ix_i18n_translations_id'), 'i18n_translations', ['id'], unique=False)
    op.create_index(op.f('ix_i18n_translations_is_active'), 'i18n_translations', ['is_active'], unique=False)
    op.create_index(op.f('ix_i18n_translations_locale_code'), 'i18n_translations', ['locale_code'], unique=False)
    op.create_index('ix_i18n_translations_lookup', 'i18n_translations', ['locale_code', 'translation_key', 'is_active'], unique=False)
    op.create_index(op.f('ix_i18n_translations_namespace'), 'i18n_translations', ['namespace'], unique=False)
    op.create_index(op.f('ix_i18n_translations_translation_key'), 'i18n_translations', ['translation_key'], unique=False)
    op.create_table('user_locale_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('locale_code', sa.String(length=20), nullable=False),
    sa.Column('timezone', sa.String(length=100), nullable=True),
    sa.Column('currency_code', sa.String(length=10), nullable=True),
    sa.Column('date_format', sa.String(length=50), nullable=True),
    sa.Column('time_format', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['locale_code'], ['i18n_locales.code'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_locale_preferences_user')
    )
    op.create_index(op.f('ix_user_locale_preferences_id'), 'user_locale_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_user_locale_preferences_locale_code'), 'user_locale_preferences', ['locale_code'], unique=False)
    op.create_index('ix_user_locale_preferences_locale_user', 'user_locale_preferences', ['locale_code', 'user_id'], unique=False)
    op.create_index(op.f('ix_user_locale_preferences_user_id'), 'user_locale_preferences', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_locale_preferences_user_id'), table_name='user_locale_preferences')
    op.drop_index('ix_user_locale_preferences_locale_user', table_name='user_locale_preferences')
    op.drop_index(op.f('ix_user_locale_preferences_locale_code'), table_name='user_locale_preferences')
    op.drop_index(op.f('ix_user_locale_preferences_id'), table_name='user_locale_preferences')
    op.drop_table('user_locale_preferences')
    op.drop_index(op.f('ix_i18n_translations_translation_key'), table_name='i18n_translations')
    op.drop_index(op.f('ix_i18n_translations_namespace'), table_name='i18n_translations')
    op.drop_index('ix_i18n_translations_lookup', table_name='i18n_translations')
    op.drop_index(op.f('ix_i18n_translations_locale_code'), table_name='i18n_translations')
    op.drop_index(op.f('ix_i18n_translations_is_active'), table_name='i18n_translations')
    op.drop_index(op.f('ix_i18n_translations_id'), table_name='i18n_translations')
    op.drop_table('i18n_translations')
    op.drop_index(op.f('ix_i18n_locales_is_default'), table_name='i18n_locales')
    op.drop_index(op.f('ix_i18n_locales_is_active'), table_name='i18n_locales')
    op.drop_index(op.f('ix_i18n_locales_fallback_locale_code'), table_name='i18n_locales')
    op.drop_index('ix_i18n_locales_active_default', table_name='i18n_locales')
    op.drop_table('i18n_locales')
    # ### end Alembic commands ###
