"""add admin mfa credentials

Revision ID: 53ce4c69b5a0
Revises: 310b99237764
Create Date: 2026-07-13 15:54:14.485086

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53ce4c69b5a0'
down_revision: Union[str, Sequence[str], None] = '310b99237764'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_security_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registration_enabled', sa.Boolean(), nullable=False),
    sa.Column('verification_required', sa.Boolean(), nullable=False),
    sa.Column('verification_method', sa.String(length=40), nullable=False),
    sa.Column('allow_login_before_verification', sa.Boolean(), nullable=False),
    sa.Column('otp_length', sa.Integer(), nullable=False),
    sa.Column('otp_expiration_minutes', sa.Integer(), nullable=False),
    sa.Column('otp_max_attempts', sa.Integer(), nullable=False),
    sa.Column('otp_resend_cooldown_seconds', sa.Integer(), nullable=False),
    sa.Column('otp_max_resends_per_hour', sa.Integer(), nullable=False),
    sa.Column('email_link_expiration_minutes', sa.Integer(), nullable=False),
    sa.Column('delete_unverified_accounts_after_days', sa.Integer(), nullable=False),
    sa.Column('turnstile_enabled', sa.Boolean(), nullable=False),
    sa.Column('block_disposable_email', sa.Boolean(), nullable=False),
    sa.Column('require_terms_acceptance', sa.Boolean(), nullable=False),
    sa.Column('require_age_confirmation', sa.Boolean(), nullable=False),
    sa.Column('minimum_age', sa.Integer(), nullable=False),
    sa.Column('max_accounts_per_ip_per_day', sa.Integer(), nullable=False),
    sa.Column('max_registrations_per_device_per_day', sa.Integer(), nullable=False),
    sa.Column('admin_mfa_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('account_verification_challenges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('purpose', sa.String(length=40), nullable=False),
    sa.Column('verification_method', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('otp_hash', sa.String(length=128), nullable=True),
    sa.Column('link_token_hash', sa.String(length=128), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('resend_count', sa.Integer(), nullable=False),
    sa.Column('requested_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_account_verification_challenge_lookup', 'account_verification_challenges', ['email', 'purpose', 'status', 'expires_at'], unique=False)
    op.create_index('ix_account_verification_challenge_user', 'account_verification_challenges', ['user_id', 'purpose', 'status'], unique=False)
    op.create_index(op.f('ix_account_verification_challenges_created_at'), 'account_verification_challenges', ['created_at'], unique=False)
    op.create_index(op.f('ix_account_verification_challenges_email'), 'account_verification_challenges', ['email'], unique=False)
    op.create_index(op.f('ix_account_verification_challenges_expires_at'), 'account_verification_challenges', ['expires_at'], unique=False)
    op.create_index(op.f('ix_account_verification_challenges_id'), 'account_verification_challenges', ['id'], unique=False)
    op.create_index(op.f('ix_account_verification_challenges_link_token_hash'), 'account_verification_challenges', ['link_token_hash'], unique=False)
    op.create_index(op.f('ix_account_verification_challenges_purpose'), 'account_verification_challenges', ['purpose'], unique=False)
    op.create_index(op.f('ix_account_verification_challenges_requested_ip'), 'account_verification_challenges', ['requested_ip'], unique=False)
    op.create_index(op.f('ix_account_verification_challenges_status'), 'account_verification_challenges', ['status'], unique=False)
    op.create_index(op.f('ix_account_verification_challenges_user_id'), 'account_verification_challenges', ['user_id'], unique=False)
    op.create_table('admin_mfa_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(length=30), nullable=False),
    sa.Column('secret_encrypted', sa.Text(), nullable=False),
    sa.Column('recovery_codes_json', sa.Text(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_mfa_credentials_id'), 'admin_mfa_credentials', ['id'], unique=False)
    op.create_index(op.f('ix_admin_mfa_credentials_is_enabled'), 'admin_mfa_credentials', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_admin_mfa_credentials_user_id'), 'admin_mfa_credentials', ['user_id'], unique=True)
    op.create_table('user_account_security',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_status', sa.String(length=40), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(), nullable=True),
    sa.Column('verification_required', sa.Boolean(), nullable=False),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_ip', sa.String(length=64), nullable=True),
    sa.Column('terms_accepted', sa.Boolean(), nullable=False),
    sa.Column('terms_version', sa.String(length=100), nullable=True),
    sa.Column('terms_accepted_at', sa.DateTime(), nullable=True),
    sa.Column('age_confirmed', sa.Boolean(), nullable=False),
    sa.Column('age_confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_account_security_user')
    )
    op.create_index(op.f('ix_user_account_security_account_status'), 'user_account_security', ['account_status'], unique=False)
    op.create_index(op.f('ix_user_account_security_created_at'), 'user_account_security', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_account_security_email_verified'), 'user_account_security', ['email_verified'], unique=False)
    op.create_index(op.f('ix_user_account_security_id'), 'user_account_security', ['id'], unique=False)
    op.create_index(op.f('ix_user_account_security_locked_until'), 'user_account_security', ['locked_until'], unique=False)
    op.create_index('ix_user_account_security_status', 'user_account_security', ['account_status', 'email_verified', 'locked_until'], unique=False)
    op.create_index(op.f('ix_user_account_security_user_id'), 'user_account_security', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_account_security_user_id'), table_name='user_account_security')
    op.drop_index('ix_user_account_security_status', table_name='user_account_security')
    op.drop_index(op.f('ix_user_account_security_locked_until'), table_name='user_account_security')
    op.drop_index(op.f('ix_user_account_security_id'), table_name='user_account_security')
    op.drop_index(op.f('ix_user_account_security_email_verified'), table_name='user_account_security')
    op.drop_index(op.f('ix_user_account_security_created_at'), table_name='user_account_security')
    op.drop_index(op.f('ix_user_account_security_account_status'), table_name='user_account_security')
    op.drop_table('user_account_security')
    op.drop_index(op.f('ix_admin_mfa_credentials_user_id'), table_name='admin_mfa_credentials')
    op.drop_index(op.f('ix_admin_mfa_credentials_is_enabled'), table_name='admin_mfa_credentials')
    op.drop_index(op.f('ix_admin_mfa_credentials_id'), table_name='admin_mfa_credentials')
    op.drop_table('admin_mfa_credentials')
    op.drop_index(op.f('ix_account_verification_challenges_user_id'), table_name='account_verification_challenges')
    op.drop_index(op.f('ix_account_verification_challenges_status'), table_name='account_verification_challenges')
    op.drop_index(op.f('ix_account_verification_challenges_requested_ip'), table_name='account_verification_challenges')
    op.drop_index(op.f('ix_account_verification_challenges_purpose'), table_name='account_verification_challenges')
    op.drop_index(op.f('ix_account_verification_challenges_link_token_hash'), table_name='account_verification_challenges')
    op.drop_index(op.f('ix_account_verification_challenges_id'), table_name='account_verification_challenges')
    op.drop_index(op.f('ix_account_verification_challenges_expires_at'), table_name='account_verification_challenges')
    op.drop_index(op.f('ix_account_verification_challenges_email'), table_name='account_verification_challenges')
    op.drop_index(op.f('ix_account_verification_challenges_created_at'), table_name='account_verification_challenges')
    op.drop_index('ix_account_verification_challenge_user', table_name='account_verification_challenges')
    op.drop_index('ix_account_verification_challenge_lookup', table_name='account_verification_challenges')
    op.drop_table('account_verification_challenges')
    op.drop_table('account_security_settings')
    # ### end Alembic commands ###
