"""add email change requests

Revision ID: 63f37a0bd886
Revises: 79c16e15b7e6
Create Date: 2026-07-13 19:54:20.715658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '63f37a0bd886'
down_revision: Union[str, Sequence[str], None] = '79c16e15b7e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_change_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('current_email', sa.String(length=320), nullable=False),
    sa.Column('new_email', sa.String(length=320), nullable=False),
    sa.Column('verification_method', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('otp_hash', sa.String(length=128), nullable=True),
    sa.Column('link_token_hash', sa.String(length=128), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('resend_count', sa.Integer(), nullable=False),
    sa.Column('requested_ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_sent_at', sa.DateTime(), nullable=False),
    sa.Column('verified_at', sa.DateTime(), nullable=True),
    sa.Column('cancelled_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_change_requests_created_at'), 'email_change_requests', ['created_at'], unique=False)
    op.create_index(op.f('ix_email_change_requests_current_email'), 'email_change_requests', ['current_email'], unique=False)
    op.create_index(op.f('ix_email_change_requests_expires_at'), 'email_change_requests', ['expires_at'], unique=False)
    op.create_index(op.f('ix_email_change_requests_id'), 'email_change_requests', ['id'], unique=False)
    op.create_index(op.f('ix_email_change_requests_link_token_hash'), 'email_change_requests', ['link_token_hash'], unique=False)
    op.create_index('ix_email_change_requests_lookup', 'email_change_requests', ['user_id', 'status', 'expires_at'], unique=False)
    op.create_index(op.f('ix_email_change_requests_new_email'), 'email_change_requests', ['new_email'], unique=False)
    op.create_index('ix_email_change_requests_new_email_status', 'email_change_requests', ['new_email', 'status'], unique=False)
    op.create_index(op.f('ix_email_change_requests_status'), 'email_change_requests', ['status'], unique=False)
    op.create_index(op.f('ix_email_change_requests_user_id'), 'email_change_requests', ['user_id'], unique=False)
    op.drop_index(op.f('ix_user_gallery_items_category'), table_name='user_gallery_items')
    op.drop_index(op.f('ix_user_gallery_items_created_at'), table_name='user_gallery_items')
    op.drop_index(op.f('ix_user_gallery_items_deleted_at'), table_name='user_gallery_items')
    op.drop_index(op.f('ix_user_gallery_items_id'), table_name='user_gallery_items')
    op.drop_index(op.f('ix_user_gallery_items_is_archived'), table_name='user_gallery_items')
    op.drop_index(op.f('ix_user_gallery_items_is_deleted'), table_name='user_gallery_items')
    op.drop_index(op.f('ix_user_gallery_items_is_favorite'), table_name='user_gallery_items')
    op.drop_index(op.f('ix_user_gallery_items_result_file_id'), table_name='user_gallery_items')
    op.drop_index(op.f('ix_user_gallery_items_source_file_id'), table_name='user_gallery_items')
    op.drop_index(op.f('ix_user_gallery_items_tryon_job_id'), table_name='user_gallery_items')
    op.drop_index(op.f('ix_user_gallery_items_user_id'), table_name='user_gallery_items')
    op.drop_index(op.f('ix_user_gallery_items_visibility'), table_name='user_gallery_items')
    op.drop_index(op.f('ix_user_gallery_owner_favorite'), table_name='user_gallery_items')
    op.drop_index(op.f('ix_user_gallery_owner_state'), table_name='user_gallery_items')
    op.drop_index(op.f('ix_user_gallery_tryon_owner'), table_name='user_gallery_items')
    op.drop_table('user_gallery_items')
    op.drop_index(op.f('ix_user_profile_settings_country_code'), table_name='user_profile_settings')
    op.drop_index(op.f('ix_user_profile_settings_gallery_visibility'), table_name='user_profile_settings')
    op.drop_index(op.f('ix_user_profile_settings_id'), table_name='user_profile_settings')
    op.drop_index(op.f('ix_user_profile_settings_locale_code'), table_name='user_profile_settings')
    op.drop_index(op.f('ix_user_profile_settings_onboarding'), table_name='user_profile_settings')
    op.drop_index(op.f('ix_user_profile_settings_onboarding_completed'), table_name='user_profile_settings')
    op.drop_index(op.f('ix_user_profile_settings_privacy'), table_name='user_profile_settings')
    op.drop_index(op.f('ix_user_profile_settings_profile_completed'), table_name='user_profile_settings')
    op.drop_index(op.f('ix_user_profile_settings_profile_visibility'), table_name='user_profile_settings')
    op.drop_index(op.f('ix_user_profile_settings_user_id'), table_name='user_profile_settings')
    op.drop_index(op.f('ix_user_profile_settings_username'), table_name='user_profile_settings')
    op.drop_table('user_profile_settings')
    op.drop_index(op.f('ix_admin_mfa_credentials_id'), table_name='admin_mfa_credentials')
    op.drop_index(op.f('ix_admin_mfa_credentials_is_enabled'), table_name='admin_mfa_credentials')
    op.drop_index(op.f('ix_admin_mfa_credentials_user_id'), table_name='admin_mfa_credentials')
    op.drop_table('admin_mfa_credentials')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_mfa_credentials',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('method', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('secret_encrypted', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('recovery_codes_json', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('is_enabled', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('verified_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('last_used_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('admin_mfa_credentials_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('admin_mfa_credentials_pkey'))
    )
    op.create_index(op.f('ix_admin_mfa_credentials_user_id'), 'admin_mfa_credentials', ['user_id'], unique=True)
    op.create_index(op.f('ix_admin_mfa_credentials_is_enabled'), 'admin_mfa_credentials', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_admin_mfa_credentials_id'), 'admin_mfa_credentials', ['id'], unique=False)
    op.create_table('user_profile_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('biography', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('country_code', sa.VARCHAR(length=2), autoincrement=False, nullable=True),
    sa.Column('timezone', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('locale_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('currency_code', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('profile_visibility', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('gallery_visibility', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('show_activity_status', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('allow_marketing_emails', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('allow_product_updates', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('allow_security_emails', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('image_processing_consent', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('image_processing_consent_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('retain_input_images', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('retain_generated_images', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('profile_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('onboarding_completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('onboarding_completed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_profile_settings_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_profile_settings_pkey'))
    )
    op.create_index(op.f('ix_user_profile_settings_username'), 'user_profile_settings', ['username'], unique=True)
    op.create_index(op.f('ix_user_profile_settings_user_id'), 'user_profile_settings', ['user_id'], unique=True)
    op.create_index(op.f('ix_user_profile_settings_profile_visibility'), 'user_profile_settings', ['profile_visibility'], unique=False)
    op.create_index(op.f('ix_user_profile_settings_profile_completed'), 'user_profile_settings', ['profile_completed'], unique=False)
    op.create_index(op.f('ix_user_profile_settings_privacy'), 'user_profile_settings', ['profile_visibility', 'gallery_visibility'], unique=False)
    op.create_index(op.f('ix_user_profile_settings_onboarding_completed'), 'user_profile_settings', ['onboarding_completed'], unique=False)
    op.create_index(op.f('ix_user_profile_settings_onboarding'), 'user_profile_settings', ['profile_completed', 'onboarding_completed'], unique=False)
    op.create_index(op.f('ix_user_profile_settings_locale_code'), 'user_profile_settings', ['locale_code'], unique=False)
    op.create_index(op.f('ix_user_profile_settings_id'), 'user_profile_settings', ['id'], unique=False)
    op.create_index(op.f('ix_user_profile_settings_gallery_visibility'), 'user_profile_settings', ['gallery_visibility'], unique=False)
    op.create_index(op.f('ix_user_profile_settings_country_code'), 'user_profile_settings', ['country_code'], unique=False)
    op.create_table('user_gallery_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('tryon_job_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('source_file_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('result_file_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('visibility', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('is_favorite', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_archived', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('is_deleted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('deleted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['result_file_id'], ['storage_files.id'], name=op.f('user_gallery_items_result_file_id_fkey'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_file_id'], ['storage_files.id'], name=op.f('user_gallery_items_source_file_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tryon_job_id'], ['tryon_jobs.id'], name=op.f('user_gallery_items_tryon_job_id_fkey'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_gallery_items_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_gallery_items_pkey'))
    )
    op.create_index(op.f('ix_user_gallery_tryon_owner'), 'user_gallery_items', ['tryon_job_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_user_gallery_owner_state'), 'user_gallery_items', ['user_id', 'is_deleted', 'is_archived'], unique=False)
    op.create_index(op.f('ix_user_gallery_owner_favorite'), 'user_gallery_items', ['user_id', 'is_favorite', 'created_at'], unique=False)
    op.create_index(op.f('ix_user_gallery_items_visibility'), 'user_gallery_items', ['visibility'], unique=False)
    op.create_index(op.f('ix_user_gallery_items_user_id'), 'user_gallery_items', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_gallery_items_tryon_job_id'), 'user_gallery_items', ['tryon_job_id'], unique=False)
    op.create_index(op.f('ix_user_gallery_items_source_file_id'), 'user_gallery_items', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_user_gallery_items_result_file_id'), 'user_gallery_items', ['result_file_id'], unique=False)
    op.create_index(op.f('ix_user_gallery_items_is_favorite'), 'user_gallery_items', ['is_favorite'], unique=False)
    op.create_index(op.f('ix_user_gallery_items_is_deleted'), 'user_gallery_items', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_gallery_items_is_archived'), 'user_gallery_items', ['is_archived'], unique=False)
    op.create_index(op.f('ix_user_gallery_items_id'), 'user_gallery_items', ['id'], unique=False)
    op.create_index(op.f('ix_user_gallery_items_deleted_at'), 'user_gallery_items', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_user_gallery_items_created_at'), 'user_gallery_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_gallery_items_category'), 'user_gallery_items', ['category'], unique=False)
    op.drop_index(op.f('ix_email_change_requests_user_id'), table_name='email_change_requests')
    op.drop_index(op.f('ix_email_change_requests_status'), table_name='email_change_requests')
    op.drop_index('ix_email_change_requests_new_email_status', table_name='email_change_requests')
    op.drop_index(op.f('ix_email_change_requests_new_email'), table_name='email_change_requests')
    op.drop_index('ix_email_change_requests_lookup', table_name='email_change_requests')
    op.drop_index(op.f('ix_email_change_requests_link_token_hash'), table_name='email_change_requests')
    op.drop_index(op.f('ix_email_change_requests_id'), table_name='email_change_requests')
    op.drop_index(op.f('ix_email_change_requests_expires_at'), table_name='email_change_requests')
    op.drop_index(op.f('ix_email_change_requests_current_email'), table_name='email_change_requests')
    op.drop_index(op.f('ix_email_change_requests_created_at'), table_name='email_change_requests')
    op.drop_table('email_change_requests')
    # ### end Alembic commands ###
