"""complete advanced audit entries

Revision ID: 6a324dc7ae78
Revises: 60be102b7d8d
Create Date: 2026-07-12 14:09:07.108574

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a324dc7ae78'
down_revision: Union[str, Sequence[str], None] = '60be102b7d8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('actor_type', sa.String(length=30), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=120), nullable=False),
    sa.Column('entity_id', sa.String(length=120), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('before_data', sa.JSON(), nullable=True),
    sa.Column('after_data', sa.JSON(), nullable=True),
    sa.Column('diff_data', sa.JSON(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.Column('request_id', sa.String(length=128), nullable=True),
    sa.Column('error_type', sa.String(length=255), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('is_restorable', sa.Boolean(), nullable=False),
    sa.Column('restored_from_entry_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['restored_from_entry_id'], ['audit_entries.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_entries_action'), 'audit_entries', ['action'], unique=False)
    op.create_index('ix_audit_entries_action_date', 'audit_entries', ['action', 'created_at'], unique=False)
    op.create_index('ix_audit_entries_actor_date', 'audit_entries', ['actor_user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_entries_actor_email'), 'audit_entries', ['actor_email'], unique=False)
    op.create_index(op.f('ix_audit_entries_actor_type'), 'audit_entries', ['actor_type'], unique=False)
    op.create_index(op.f('ix_audit_entries_actor_user_id'), 'audit_entries', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_entries_correlation_id'), 'audit_entries', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_entries_created_at'), 'audit_entries', ['created_at'], unique=False)
    op.create_index('ix_audit_entries_entity', 'audit_entries', ['entity_type', 'entity_id'], unique=False)
    op.create_index('ix_audit_entries_entity_date', 'audit_entries', ['entity_type', 'entity_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_entries_entity_id'), 'audit_entries', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_entries_entity_type'), 'audit_entries', ['entity_type'], unique=False)
    op.create_index(op.f('ix_audit_entries_error_type'), 'audit_entries', ['error_type'], unique=False)
    op.create_index(op.f('ix_audit_entries_id'), 'audit_entries', ['id'], unique=False)
    op.create_index(op.f('ix_audit_entries_ip_address'), 'audit_entries', ['ip_address'], unique=False)
    op.create_index(op.f('ix_audit_entries_is_restorable'), 'audit_entries', ['is_restorable'], unique=False)
    op.create_index(op.f('ix_audit_entries_request_id'), 'audit_entries', ['request_id'], unique=False)
    op.create_index(op.f('ix_audit_entries_restored_from_entry_id'), 'audit_entries', ['restored_from_entry_id'], unique=False)
    op.create_index('ix_audit_entries_result_date', 'audit_entries', ['success', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_entries_success'), 'audit_entries', ['success'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_entries_success'), table_name='audit_entries')
    op.drop_index('ix_audit_entries_result_date', table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_restored_from_entry_id'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_request_id'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_is_restorable'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_ip_address'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_id'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_error_type'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_entity_type'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_entity_id'), table_name='audit_entries')
    op.drop_index('ix_audit_entries_entity_date', table_name='audit_entries')
    op.drop_index('ix_audit_entries_entity', table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_created_at'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_correlation_id'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_actor_user_id'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_actor_type'), table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_actor_email'), table_name='audit_entries')
    op.drop_index('ix_audit_entries_actor_date', table_name='audit_entries')
    op.drop_index('ix_audit_entries_action_date', table_name='audit_entries')
    op.drop_index(op.f('ix_audit_entries_action'), table_name='audit_entries')
    op.drop_table('audit_entries')
    # ### end Alembic commands ###
