"""add user gallery items

Revision ID: 79c16e15b7e6
Revises: 933be52cae6d
Create Date: 2026-07-13 16:34:17.231936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79c16e15b7e6'
down_revision: Union[str, Sequence[str], None] = '933be52cae6d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_gallery_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tryon_job_id', sa.Integer(), nullable=True),
    sa.Column('source_file_id', sa.Integer(), nullable=True),
    sa.Column('result_file_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('visibility', sa.String(length=30), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['result_file_id'], ['storage_files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_file_id'], ['storage_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tryon_job_id'], ['tryon_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_gallery_items_category'), 'user_gallery_items', ['category'], unique=False)
    op.create_index(op.f('ix_user_gallery_items_created_at'), 'user_gallery_items', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_gallery_items_deleted_at'), 'user_gallery_items', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_user_gallery_items_id'), 'user_gallery_items', ['id'], unique=False)
    op.create_index(op.f('ix_user_gallery_items_is_archived'), 'user_gallery_items', ['is_archived'], unique=False)
    op.create_index(op.f('ix_user_gallery_items_is_deleted'), 'user_gallery_items', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_gallery_items_is_favorite'), 'user_gallery_items', ['is_favorite'], unique=False)
    op.create_index(op.f('ix_user_gallery_items_result_file_id'), 'user_gallery_items', ['result_file_id'], unique=False)
    op.create_index(op.f('ix_user_gallery_items_source_file_id'), 'user_gallery_items', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_user_gallery_items_tryon_job_id'), 'user_gallery_items', ['tryon_job_id'], unique=False)
    op.create_index(op.f('ix_user_gallery_items_user_id'), 'user_gallery_items', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_gallery_items_visibility'), 'user_gallery_items', ['visibility'], unique=False)
    op.create_index('ix_user_gallery_owner_favorite', 'user_gallery_items', ['user_id', 'is_favorite', 'created_at'], unique=False)
    op.create_index('ix_user_gallery_owner_state', 'user_gallery_items', ['user_id', 'is_deleted', 'is_archived'], unique=False)
    op.create_index('ix_user_gallery_tryon_owner', 'user_gallery_items', ['tryon_job_id', 'user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_gallery_tryon_owner', table_name='user_gallery_items')
    op.drop_index('ix_user_gallery_owner_state', table_name='user_gallery_items')
    op.drop_index('ix_user_gallery_owner_favorite', table_name='user_gallery_items')
    op.drop_index(op.f('ix_user_gallery_items_visibility'), table_name='user_gallery_items')
    op.drop_index(op.f('ix_user_gallery_items_user_id'), table_name='user_gallery_items')
    op.drop_index(op.f('ix_user_gallery_items_tryon_job_id'), table_name='user_gallery_items')
    op.drop_index(op.f('ix_user_gallery_items_source_file_id'), table_name='user_gallery_items')
    op.drop_index(op.f('ix_user_gallery_items_result_file_id'), table_name='user_gallery_items')
    op.drop_index(op.f('ix_user_gallery_items_is_favorite'), table_name='user_gallery_items')
    op.drop_index(op.f('ix_user_gallery_items_is_deleted'), table_name='user_gallery_items')
    op.drop_index(op.f('ix_user_gallery_items_is_archived'), table_name='user_gallery_items')
    op.drop_index(op.f('ix_user_gallery_items_id'), table_name='user_gallery_items')
    op.drop_index(op.f('ix_user_gallery_items_deleted_at'), table_name='user_gallery_items')
    op.drop_index(op.f('ix_user_gallery_items_created_at'), table_name='user_gallery_items')
    op.drop_index(op.f('ix_user_gallery_items_category'), table_name='user_gallery_items')
    op.drop_table('user_gallery_items')
    # ### end Alembic commands ###
