"""add user notification center

Revision ID: 8bbe4662fab7
Revises: 22a5cd2a04fc
Create Date: 2026-07-12 16:12:39.154729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bbe4662fab7'
down_revision: Union[str, Sequence[str], None] = '22a5cd2a04fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('recipient_user_id', sa.Integer(), nullable=True),
    sa.Column('notification_type', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('source', sa.String(length=60), nullable=False),
    sa.Column('event_type', sa.String(length=150), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('action_url', sa.String(length=2000), nullable=True),
    sa.Column('action_label', sa.String(length=120), nullable=True),
    sa.Column('entity_type', sa.String(length=120), nullable=True),
    sa.Column('entity_id', sa.String(length=150), nullable=True),
    sa.Column('image_url', sa.String(length=2000), nullable=True),
    sa.Column('correlation_id', sa.String(length=128), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('is_global', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('requires_action', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_notifications_correlation_id'), 'user_notifications', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_user_notifications_created_at'), 'user_notifications', ['created_at'], unique=False)
    op.create_index('ix_user_notifications_entity', 'user_notifications', ['entity_type', 'entity_id'], unique=False)
    op.create_index(op.f('ix_user_notifications_entity_id'), 'user_notifications', ['entity_id'], unique=False)
    op.create_index(op.f('ix_user_notifications_entity_type'), 'user_notifications', ['entity_type'], unique=False)
    op.create_index(op.f('ix_user_notifications_event_type'), 'user_notifications', ['event_type'], unique=False)
    op.create_index(op.f('ix_user_notifications_expires_at'), 'user_notifications', ['expires_at'], unique=False)
    op.create_index('ix_user_notifications_global_published', 'user_notifications', ['is_global', 'is_active', 'published_at'], unique=False)
    op.create_index(op.f('ix_user_notifications_id'), 'user_notifications', ['id'], unique=False)
    op.create_index(op.f('ix_user_notifications_is_active'), 'user_notifications', ['is_active'], unique=False)
    op.create_index(op.f('ix_user_notifications_is_global'), 'user_notifications', ['is_global'], unique=False)
    op.create_index(op.f('ix_user_notifications_notification_type'), 'user_notifications', ['notification_type'], unique=False)
    op.create_index(op.f('ix_user_notifications_priority'), 'user_notifications', ['priority'], unique=False)
    op.create_index(op.f('ix_user_notifications_published_at'), 'user_notifications', ['published_at'], unique=False)
    op.create_index('ix_user_notifications_recipient_created', 'user_notifications', ['recipient_user_id', 'is_active', 'created_at'], unique=False)
    op.create_index(op.f('ix_user_notifications_recipient_user_id'), 'user_notifications', ['recipient_user_id'], unique=False)
    op.create_index(op.f('ix_user_notifications_requires_action'), 'user_notifications', ['requires_action'], unique=False)
    op.create_index(op.f('ix_user_notifications_source'), 'user_notifications', ['source'], unique=False)
    op.create_index('ix_user_notifications_source_event', 'user_notifications', ['source', 'event_type', 'created_at'], unique=False)
    op.create_table('user_notification_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notification_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.Column('archived_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['notification_id'], ['user_notifications.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('notification_id', 'user_id', name='uq_user_notification_receipt_notification_user')
    )
    op.create_index(op.f('ix_user_notification_receipts_created_at'), 'user_notification_receipts', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_notification_receipts_id'), 'user_notification_receipts', ['id'], unique=False)
    op.create_index(op.f('ix_user_notification_receipts_is_archived'), 'user_notification_receipts', ['is_archived'], unique=False)
    op.create_index(op.f('ix_user_notification_receipts_is_read'), 'user_notification_receipts', ['is_read'], unique=False)
    op.create_index(op.f('ix_user_notification_receipts_notification_id'), 'user_notification_receipts', ['notification_id'], unique=False)
    op.create_index('ix_user_notification_receipts_status', 'user_notification_receipts', ['user_id', 'is_read', 'is_archived'], unique=False)
    op.create_index(op.f('ix_user_notification_receipts_user_id'), 'user_notification_receipts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_notification_receipts_user_id'), table_name='user_notification_receipts')
    op.drop_index('ix_user_notification_receipts_status', table_name='user_notification_receipts')
    op.drop_index(op.f('ix_user_notification_receipts_notification_id'), table_name='user_notification_receipts')
    op.drop_index(op.f('ix_user_notification_receipts_is_read'), table_name='user_notification_receipts')
    op.drop_index(op.f('ix_user_notification_receipts_is_archived'), table_name='user_notification_receipts')
    op.drop_index(op.f('ix_user_notification_receipts_id'), table_name='user_notification_receipts')
    op.drop_index(op.f('ix_user_notification_receipts_created_at'), table_name='user_notification_receipts')
    op.drop_table('user_notification_receipts')
    op.drop_index('ix_user_notifications_source_event', table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_source'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_requires_action'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_recipient_user_id'), table_name='user_notifications')
    op.drop_index('ix_user_notifications_recipient_created', table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_published_at'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_priority'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_notification_type'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_is_global'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_is_active'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_id'), table_name='user_notifications')
    op.drop_index('ix_user_notifications_global_published', table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_expires_at'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_event_type'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_entity_type'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_entity_id'), table_name='user_notifications')
    op.drop_index('ix_user_notifications_entity', table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_created_at'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_correlation_id'), table_name='user_notifications')
    op.drop_table('user_notifications')
    # ### end Alembic commands ###
