"""add user notification preferences and push subscriptions

Revision ID: 8f30b664416e
Revises: 8bbe4662fab7
Create Date: 2026-07-12 16:34:08.867776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f30b664416e'
down_revision: Union[str, Sequence[str], None] = '8bbe4662fab7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_notification_preferences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('in_app_enabled', sa.Boolean(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=False),
    sa.Column('web_push_enabled', sa.Boolean(), nullable=False),
    sa.Column('marketing_enabled', sa.Boolean(), nullable=False),
    sa.Column('tryon_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('billing_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('token_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('subscription_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('support_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('security_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('announcement_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('minimum_priority', sa.String(length=30), nullable=False),
    sa.Column('email_minimum_priority', sa.String(length=30), nullable=False),
    sa.Column('web_push_minimum_priority', sa.String(length=30), nullable=False),
    sa.Column('quiet_hours_enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sa.Time(), nullable=True),
    sa.Column('quiet_hours_end', sa.Time(), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('allow_urgent_during_quiet_hours', sa.Boolean(), nullable=False),
    sa.Column('disabled_event_types_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_user_notification_preferences_user')
    )
    op.create_index('ix_user_notification_preferences_channels', 'user_notification_preferences', ['in_app_enabled', 'email_enabled', 'web_push_enabled'], unique=False)
    op.create_index(op.f('ix_user_notification_preferences_created_at'), 'user_notification_preferences', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_notification_preferences_id'), 'user_notification_preferences', ['id'], unique=False)
    op.create_index(op.f('ix_user_notification_preferences_minimum_priority'), 'user_notification_preferences', ['minimum_priority'], unique=False)
    op.create_index(op.f('ix_user_notification_preferences_user_id'), 'user_notification_preferences', ['user_id'], unique=True)
    op.create_table('user_push_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=False),
    sa.Column('endpoint_hash', sa.String(length=64), nullable=False),
    sa.Column('p256dh_key', sa.Text(), nullable=False),
    sa.Column('auth_key', sa.Text(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('device_name', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('endpoint_hash', name='uq_user_push_subscriptions_endpoint_hash')
    )
    op.create_index(op.f('ix_user_push_subscriptions_created_at'), 'user_push_subscriptions', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_push_subscriptions_endpoint_hash'), 'user_push_subscriptions', ['endpoint_hash'], unique=True)
    op.create_index(op.f('ix_user_push_subscriptions_id'), 'user_push_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_user_push_subscriptions_is_active'), 'user_push_subscriptions', ['is_active'], unique=False)
    op.create_index('ix_user_push_subscriptions_user_active', 'user_push_subscriptions', ['user_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_user_push_subscriptions_user_id'), 'user_push_subscriptions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_push_subscriptions_user_id'), table_name='user_push_subscriptions')
    op.drop_index('ix_user_push_subscriptions_user_active', table_name='user_push_subscriptions')
    op.drop_index(op.f('ix_user_push_subscriptions_is_active'), table_name='user_push_subscriptions')
    op.drop_index(op.f('ix_user_push_subscriptions_id'), table_name='user_push_subscriptions')
    op.drop_index(op.f('ix_user_push_subscriptions_endpoint_hash'), table_name='user_push_subscriptions')
    op.drop_index(op.f('ix_user_push_subscriptions_created_at'), table_name='user_push_subscriptions')
    op.drop_table('user_push_subscriptions')
    op.drop_index(op.f('ix_user_notification_preferences_user_id'), table_name='user_notification_preferences')
    op.drop_index(op.f('ix_user_notification_preferences_minimum_priority'), table_name='user_notification_preferences')
    op.drop_index(op.f('ix_user_notification_preferences_id'), table_name='user_notification_preferences')
    op.drop_index(op.f('ix_user_notification_preferences_created_at'), table_name='user_notification_preferences')
    op.drop_index('ix_user_notification_preferences_channels', table_name='user_notification_preferences')
    op.drop_table('user_notification_preferences')
    # ### end Alembic commands ###
