"""add user profile privacy and onboarding settings

Revision ID: 933be52cae6d
Revises: 53ce4c69b5a0
Create Date: 2026-07-13 16:22:21.247283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '933be52cae6d'
down_revision: Union[str, Sequence[str], None] = '53ce4c69b5a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('biography', sa.Text(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('timezone', sa.String(length=100), nullable=False),
    sa.Column('locale_code', sa.String(length=20), nullable=False),
    sa.Column('currency_code', sa.String(length=10), nullable=False),
    sa.Column('profile_visibility', sa.String(length=30), nullable=False),
    sa.Column('gallery_visibility', sa.String(length=30), nullable=False),
    sa.Column('show_activity_status', sa.Boolean(), nullable=False),
    sa.Column('allow_marketing_emails', sa.Boolean(), nullable=False),
    sa.Column('allow_product_updates', sa.Boolean(), nullable=False),
    sa.Column('allow_security_emails', sa.Boolean(), nullable=False),
    sa.Column('image_processing_consent', sa.Boolean(), nullable=False),
    sa.Column('image_processing_consent_at', sa.DateTime(), nullable=True),
    sa.Column('retain_input_images', sa.Boolean(), nullable=False),
    sa.Column('retain_generated_images', sa.Boolean(), nullable=False),
    sa.Column('profile_completed', sa.Boolean(), nullable=False),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('onboarding_completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profile_settings_country_code'), 'user_profile_settings', ['country_code'], unique=False)
    op.create_index(op.f('ix_user_profile_settings_gallery_visibility'), 'user_profile_settings', ['gallery_visibility'], unique=False)
    op.create_index(op.f('ix_user_profile_settings_id'), 'user_profile_settings', ['id'], unique=False)
    op.create_index(op.f('ix_user_profile_settings_locale_code'), 'user_profile_settings', ['locale_code'], unique=False)
    op.create_index('ix_user_profile_settings_onboarding', 'user_profile_settings', ['profile_completed', 'onboarding_completed'], unique=False)
    op.create_index(op.f('ix_user_profile_settings_onboarding_completed'), 'user_profile_settings', ['onboarding_completed'], unique=False)
    op.create_index('ix_user_profile_settings_privacy', 'user_profile_settings', ['profile_visibility', 'gallery_visibility'], unique=False)
    op.create_index(op.f('ix_user_profile_settings_profile_completed'), 'user_profile_settings', ['profile_completed'], unique=False)
    op.create_index(op.f('ix_user_profile_settings_profile_visibility'), 'user_profile_settings', ['profile_visibility'], unique=False)
    op.create_index(op.f('ix_user_profile_settings_user_id'), 'user_profile_settings', ['user_id'], unique=True)
    op.create_index(op.f('ix_user_profile_settings_username'), 'user_profile_settings', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profile_settings_username'), table_name='user_profile_settings')
    op.drop_index(op.f('ix_user_profile_settings_user_id'), table_name='user_profile_settings')
    op.drop_index(op.f('ix_user_profile_settings_profile_visibility'), table_name='user_profile_settings')
    op.drop_index(op.f('ix_user_profile_settings_profile_completed'), table_name='user_profile_settings')
    op.drop_index('ix_user_profile_settings_privacy', table_name='user_profile_settings')
    op.drop_index(op.f('ix_user_profile_settings_onboarding_completed'), table_name='user_profile_settings')
    op.drop_index('ix_user_profile_settings_onboarding', table_name='user_profile_settings')
    op.drop_index(op.f('ix_user_profile_settings_locale_code'), table_name='user_profile_settings')
    op.drop_index(op.f('ix_user_profile_settings_id'), table_name='user_profile_settings')
    op.drop_index(op.f('ix_user_profile_settings_gallery_visibility'), table_name='user_profile_settings')
    op.drop_index(op.f('ix_user_profile_settings_country_code'), table_name='user_profile_settings')
    op.drop_table('user_profile_settings')
    # ### end Alembic commands ###
