"""add complete billing models

Revision ID: 957d97d3ee3c
Revises: aeb84b324894
Create Date: 2026-07-10 00:06:32.062551

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '957d97d3ee3c'
down_revision: Union[str, Sequence[str], None] = 'aeb84b324894'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billing_coupons',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('discount_type', sa.String(length=50), nullable=False),
    sa.Column('percentage_off', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('amount_off', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('stripe_coupon_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_promotion_code_id', sa.String(length=255), nullable=True),
    sa.Column('max_redemptions', sa.Integer(), nullable=True),
    sa.Column('redemption_count', sa.Integer(), nullable=False),
    sa.Column('valid_from', sa.DateTime(), nullable=True),
    sa.Column('valid_until', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_coupons_code'), 'billing_coupons', ['code'], unique=True)
    op.create_index(op.f('ix_billing_coupons_id'), 'billing_coupons', ['id'], unique=False)
    op.create_index(op.f('ix_billing_coupons_is_active'), 'billing_coupons', ['is_active'], unique=False)
    op.create_index(op.f('ix_billing_coupons_stripe_coupon_id'), 'billing_coupons', ['stripe_coupon_id'], unique=True)
    op.create_index(op.f('ix_billing_coupons_stripe_promotion_code_id'), 'billing_coupons', ['stripe_promotion_code_id'], unique=True)
    op.create_table('billing_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_event_id', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_attempts', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_event_id', name='uq_billing_event_provider_event')
    )
    op.create_index(op.f('ix_billing_events_event_type'), 'billing_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_billing_events_id'), 'billing_events', ['id'], unique=False)
    op.create_index(op.f('ix_billing_events_provider'), 'billing_events', ['provider'], unique=False)
    op.create_index(op.f('ix_billing_events_provider_event_id'), 'billing_events', ['provider_event_id'], unique=False)
    op.create_index(op.f('ix_billing_events_received_at'), 'billing_events', ['received_at'], unique=False)
    op.create_index(op.f('ix_billing_events_status'), 'billing_events', ['status'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('billing_interval', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('price_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tokens_per_period', sa.Integer(), nullable=False),
    sa.Column('max_generations_per_period', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('stripe_product_id', sa.String(length=255), nullable=True),
    sa.Column('stripe_price_id', sa.String(length=255), nullable=True),
    sa.Column('features_json', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_plans_billing_interval'), 'subscription_plans', ['billing_interval'], unique=False)
    op.create_index(op.f('ix_subscription_plans_id'), 'subscription_plans', ['id'], unique=False)
    op.create_index(op.f('ix_subscription_plans_is_active'), 'subscription_plans', ['is_active'], unique=False)
    op.create_index(op.f('ix_subscription_plans_is_public'), 'subscription_plans', ['is_public'], unique=False)
    op.create_index(op.f('ix_subscription_plans_key'), 'subscription_plans', ['key'], unique=True)
    op.create_index(op.f('ix_subscription_plans_stripe_price_id'), 'subscription_plans', ['stripe_price_id'], unique=True)
    op.create_index(op.f('ix_subscription_plans_stripe_product_id'), 'subscription_plans', ['stripe_product_id'], unique=False)
    op.create_table('billing_customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_customer_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_customer_id', name='uq_billing_customer_provider_customer'),
    sa.UniqueConstraint('provider', 'user_id', name='uq_billing_customer_provider_user')
    )
    op.create_index(op.f('ix_billing_customers_id'), 'billing_customers', ['id'], unique=False)
    op.create_index(op.f('ix_billing_customers_provider'), 'billing_customers', ['provider'], unique=False)
    op.create_index(op.f('ix_billing_customers_provider_customer_id'), 'billing_customers', ['provider_customer_id'], unique=False)
    op.create_index(op.f('ix_billing_customers_user_id'), 'billing_customers', ['user_id'], unique=False)
    op.create_table('user_subscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_plan_id', sa.Integer(), nullable=False),
    sa.Column('billing_customer_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_period_start', sa.DateTime(), nullable=True),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('trial_start', sa.DateTime(), nullable=True),
    sa.Column('trial_end', sa.DateTime(), nullable=True),
    sa.Column('cancel_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('last_tokens_granted_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['billing_customer_id'], ['billing_customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_subscriptions_billing_customer_id'), 'user_subscriptions', ['billing_customer_id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_current_period_end'), 'user_subscriptions', ['current_period_end'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_id'), 'user_subscriptions', ['id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_provider'), 'user_subscriptions', ['provider'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_provider_subscription_id'), 'user_subscriptions', ['provider_subscription_id'], unique=True)
    op.create_index(op.f('ix_user_subscriptions_status'), 'user_subscriptions', ['status'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_subscription_plan_id'), 'user_subscriptions', ['subscription_plan_id'], unique=False)
    op.create_index(op.f('ix_user_subscriptions_user_id'), 'user_subscriptions', ['user_id'], unique=False)
    op.create_table('billing_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('billing_customer_id', sa.Integer(), nullable=True),
    sa.Column('user_subscription_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('payment_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('refunded_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('provider_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('provider_charge_id', sa.String(length=255), nullable=True),
    sa.Column('provider_checkout_session_id', sa.String(length=255), nullable=True),
    sa.Column('failure_code', sa.String(length=255), nullable=True),
    sa.Column('failure_message', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('failed_at', sa.DateTime(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['billing_customer_id'], ['billing_customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_subscription_id'], ['user_subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_payments_billing_customer_id'), 'billing_payments', ['billing_customer_id'], unique=False)
    op.create_index(op.f('ix_billing_payments_id'), 'billing_payments', ['id'], unique=False)
    op.create_index(op.f('ix_billing_payments_payment_type'), 'billing_payments', ['payment_type'], unique=False)
    op.create_index(op.f('ix_billing_payments_provider'), 'billing_payments', ['provider'], unique=False)
    op.create_index(op.f('ix_billing_payments_provider_charge_id'), 'billing_payments', ['provider_charge_id'], unique=False)
    op.create_index(op.f('ix_billing_payments_provider_checkout_session_id'), 'billing_payments', ['provider_checkout_session_id'], unique=True)
    op.create_index(op.f('ix_billing_payments_provider_payment_intent_id'), 'billing_payments', ['provider_payment_intent_id'], unique=True)
    op.create_index(op.f('ix_billing_payments_status'), 'billing_payments', ['status'], unique=False)
    op.create_index(op.f('ix_billing_payments_user_id'), 'billing_payments', ['user_id'], unique=False)
    op.create_index(op.f('ix_billing_payments_user_subscription_id'), 'billing_payments', ['user_subscription_id'], unique=False)
    op.create_table('billing_invoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('billing_customer_id', sa.Integer(), nullable=True),
    sa.Column('user_subscription_id', sa.Integer(), nullable=True),
    sa.Column('billing_payment_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_invoice_id', sa.String(length=255), nullable=False),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('hosted_invoice_url', sa.Text(), nullable=True),
    sa.Column('invoice_pdf_url', sa.Text(), nullable=True),
    sa.Column('period_start', sa.DateTime(), nullable=True),
    sa.Column('period_end', sa.DateTime(), nullable=True),
    sa.Column('due_at', sa.DateTime(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['billing_customer_id'], ['billing_customers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['billing_payment_id'], ['billing_payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_subscription_id'], ['user_subscriptions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_invoices_billing_customer_id'), 'billing_invoices', ['billing_customer_id'], unique=False)
    op.create_index(op.f('ix_billing_invoices_billing_payment_id'), 'billing_invoices', ['billing_payment_id'], unique=False)
    op.create_index(op.f('ix_billing_invoices_id'), 'billing_invoices', ['id'], unique=False)
    op.create_index(op.f('ix_billing_invoices_invoice_number'), 'billing_invoices', ['invoice_number'], unique=False)
    op.create_index(op.f('ix_billing_invoices_provider_invoice_id'), 'billing_invoices', ['provider_invoice_id'], unique=True)
    op.create_index(op.f('ix_billing_invoices_status'), 'billing_invoices', ['status'], unique=False)
    op.create_index(op.f('ix_billing_invoices_user_id'), 'billing_invoices', ['user_id'], unique=False)
    op.create_index(op.f('ix_billing_invoices_user_subscription_id'), 'billing_invoices', ['user_subscription_id'], unique=False)
    op.create_table('token_purchases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_package_id', sa.Integer(), nullable=False),
    sa.Column('billing_payment_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('tokens_amount', sa.Integer(), nullable=False),
    sa.Column('bonus_tokens', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('provider_checkout_session_id', sa.String(length=255), nullable=True),
    sa.Column('provider_payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('token_transaction_id', sa.Integer(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('credited_at', sa.DateTime(), nullable=True),
    sa.Column('refunded_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['billing_payment_id'], ['billing_payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['token_package_id'], ['token_packages.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['token_transaction_id'], ['token_transactions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_token_purchases_billing_payment_id'), 'token_purchases', ['billing_payment_id'], unique=True)
    op.create_index(op.f('ix_token_purchases_id'), 'token_purchases', ['id'], unique=False)
    op.create_index(op.f('ix_token_purchases_provider_checkout_session_id'), 'token_purchases', ['provider_checkout_session_id'], unique=True)
    op.create_index(op.f('ix_token_purchases_provider_payment_intent_id'), 'token_purchases', ['provider_payment_intent_id'], unique=False)
    op.create_index(op.f('ix_token_purchases_status'), 'token_purchases', ['status'], unique=False)
    op.create_index(op.f('ix_token_purchases_token_package_id'), 'token_purchases', ['token_package_id'], unique=False)
    op.create_index(op.f('ix_token_purchases_token_transaction_id'), 'token_purchases', ['token_transaction_id'], unique=True)
    op.create_index(op.f('ix_token_purchases_user_id'), 'token_purchases', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_token_purchases_user_id'), table_name='token_purchases')
    op.drop_index(op.f('ix_token_purchases_token_transaction_id'), table_name='token_purchases')
    op.drop_index(op.f('ix_token_purchases_token_package_id'), table_name='token_purchases')
    op.drop_index(op.f('ix_token_purchases_status'), table_name='token_purchases')
    op.drop_index(op.f('ix_token_purchases_provider_payment_intent_id'), table_name='token_purchases')
    op.drop_index(op.f('ix_token_purchases_provider_checkout_session_id'), table_name='token_purchases')
    op.drop_index(op.f('ix_token_purchases_id'), table_name='token_purchases')
    op.drop_index(op.f('ix_token_purchases_billing_payment_id'), table_name='token_purchases')
    op.drop_table('token_purchases')
    op.drop_index(op.f('ix_billing_invoices_user_subscription_id'), table_name='billing_invoices')
    op.drop_index(op.f('ix_billing_invoices_user_id'), table_name='billing_invoices')
    op.drop_index(op.f('ix_billing_invoices_status'), table_name='billing_invoices')
    op.drop_index(op.f('ix_billing_invoices_provider_invoice_id'), table_name='billing_invoices')
    op.drop_index(op.f('ix_billing_invoices_invoice_number'), table_name='billing_invoices')
    op.drop_index(op.f('ix_billing_invoices_id'), table_name='billing_invoices')
    op.drop_index(op.f('ix_billing_invoices_billing_payment_id'), table_name='billing_invoices')
    op.drop_index(op.f('ix_billing_invoices_billing_customer_id'), table_name='billing_invoices')
    op.drop_table('billing_invoices')
    op.drop_index(op.f('ix_billing_payments_user_subscription_id'), table_name='billing_payments')
    op.drop_index(op.f('ix_billing_payments_user_id'), table_name='billing_payments')
    op.drop_index(op.f('ix_billing_payments_status'), table_name='billing_payments')
    op.drop_index(op.f('ix_billing_payments_provider_payment_intent_id'), table_name='billing_payments')
    op.drop_index(op.f('ix_billing_payments_provider_checkout_session_id'), table_name='billing_payments')
    op.drop_index(op.f('ix_billing_payments_provider_charge_id'), table_name='billing_payments')
    op.drop_index(op.f('ix_billing_payments_provider'), table_name='billing_payments')
    op.drop_index(op.f('ix_billing_payments_payment_type'), table_name='billing_payments')
    op.drop_index(op.f('ix_billing_payments_id'), table_name='billing_payments')
    op.drop_index(op.f('ix_billing_payments_billing_customer_id'), table_name='billing_payments')
    op.drop_table('billing_payments')
    op.drop_index(op.f('ix_user_subscriptions_user_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_subscription_plan_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_status'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_provider_subscription_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_provider'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_id'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_current_period_end'), table_name='user_subscriptions')
    op.drop_index(op.f('ix_user_subscriptions_billing_customer_id'), table_name='user_subscriptions')
    op.drop_table('user_subscriptions')
    op.drop_index(op.f('ix_billing_customers_user_id'), table_name='billing_customers')
    op.drop_index(op.f('ix_billing_customers_provider_customer_id'), table_name='billing_customers')
    op.drop_index(op.f('ix_billing_customers_provider'), table_name='billing_customers')
    op.drop_index(op.f('ix_billing_customers_id'), table_name='billing_customers')
    op.drop_table('billing_customers')
    op.drop_index(op.f('ix_subscription_plans_stripe_product_id'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_stripe_price_id'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_key'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_is_public'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_is_active'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_id'), table_name='subscription_plans')
    op.drop_index(op.f('ix_subscription_plans_billing_interval'), table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_billing_events_status'), table_name='billing_events')
    op.drop_index(op.f('ix_billing_events_received_at'), table_name='billing_events')
    op.drop_index(op.f('ix_billing_events_provider_event_id'), table_name='billing_events')
    op.drop_index(op.f('ix_billing_events_provider'), table_name='billing_events')
    op.drop_index(op.f('ix_billing_events_id'), table_name='billing_events')
    op.drop_index(op.f('ix_billing_events_event_type'), table_name='billing_events')
    op.drop_table('billing_events')
    op.drop_index(op.f('ix_billing_coupons_stripe_promotion_code_id'), table_name='billing_coupons')
    op.drop_index(op.f('ix_billing_coupons_stripe_coupon_id'), table_name='billing_coupons')
    op.drop_index(op.f('ix_billing_coupons_is_active'), table_name='billing_coupons')
    op.drop_index(op.f('ix_billing_coupons_id'), table_name='billing_coupons')
    op.drop_index(op.f('ix_billing_coupons_code'), table_name='billing_coupons')
    op.drop_table('billing_coupons')
    # ### end Alembic commands ###
