"""add enterprise rbac models

Revision ID: cfe2221eecc0
Revises: fe55a90c6a34
Create Date: 2026-07-08 22:54:31.829608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfe2221eecc0'
down_revision: Union[str, Sequence[str], None] = 'fe55a90c6a34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feature_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_permissions_id'), 'feature_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_feature_permissions_key'), 'feature_permissions', ['key'], unique=True)
    op.create_table('rbac_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('module', sa.String(length=100), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rbac_permissions_action'), 'rbac_permissions', ['action'], unique=False)
    op.create_index(op.f('ix_rbac_permissions_id'), 'rbac_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_rbac_permissions_key'), 'rbac_permissions', ['key'], unique=True)
    op.create_index(op.f('ix_rbac_permissions_module'), 'rbac_permissions', ['module'], unique=False)
    op.create_table('rbac_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rbac_roles_id'), 'rbac_roles', ['id'], unique=False)
    op.create_index(op.f('ix_rbac_roles_key'), 'rbac_roles', ['key'], unique=True)
    op.create_table('rbac_role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['rbac_permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['rbac_roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_rbac_role_permission')
    )
    op.create_index(op.f('ix_rbac_role_permissions_id'), 'rbac_role_permissions', ['id'], unique=False)
    op.create_index(op.f('ix_rbac_role_permissions_permission_id'), 'rbac_role_permissions', ['permission_id'], unique=False)
    op.create_index(op.f('ix_rbac_role_permissions_role_id'), 'rbac_role_permissions', ['role_id'], unique=False)
    op.create_table('rbac_user_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['rbac_roles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'role_id', name='uq_rbac_user_role')
    )
    op.create_index(op.f('ix_rbac_user_roles_id'), 'rbac_user_roles', ['id'], unique=False)
    op.create_index(op.f('ix_rbac_user_roles_role_id'), 'rbac_user_roles', ['role_id'], unique=False)
    op.create_index(op.f('ix_rbac_user_roles_user_id'), 'rbac_user_roles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rbac_user_roles_user_id'), table_name='rbac_user_roles')
    op.drop_index(op.f('ix_rbac_user_roles_role_id'), table_name='rbac_user_roles')
    op.drop_index(op.f('ix_rbac_user_roles_id'), table_name='rbac_user_roles')
    op.drop_table('rbac_user_roles')
    op.drop_index(op.f('ix_rbac_role_permissions_role_id'), table_name='rbac_role_permissions')
    op.drop_index(op.f('ix_rbac_role_permissions_permission_id'), table_name='rbac_role_permissions')
    op.drop_index(op.f('ix_rbac_role_permissions_id'), table_name='rbac_role_permissions')
    op.drop_table('rbac_role_permissions')
    op.drop_index(op.f('ix_rbac_roles_key'), table_name='rbac_roles')
    op.drop_index(op.f('ix_rbac_roles_id'), table_name='rbac_roles')
    op.drop_table('rbac_roles')
    op.drop_index(op.f('ix_rbac_permissions_module'), table_name='rbac_permissions')
    op.drop_index(op.f('ix_rbac_permissions_key'), table_name='rbac_permissions')
    op.drop_index(op.f('ix_rbac_permissions_id'), table_name='rbac_permissions')
    op.drop_index(op.f('ix_rbac_permissions_action'), table_name='rbac_permissions')
    op.drop_table('rbac_permissions')
    op.drop_index(op.f('ix_feature_permissions_key'), table_name='feature_permissions')
    op.drop_index(op.f('ix_feature_permissions_id'), table_name='feature_permissions')
    op.drop_table('feature_permissions')
    # ### end Alembic commands ###
