"""add system status

Revision ID: d68eeb8e2471
Revises: 7c82b0299538
Create Date: 2026-07-08 21:19:26.149409

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd68eeb8e2471'
down_revision: Union[str, Sequence[str], None] = '7c82b0299538'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('maintenance_mode', sa.Boolean(), nullable=False),
    sa.Column('registration_enabled', sa.Boolean(), nullable=False),
    sa.Column('tryon_enabled', sa.Boolean(), nullable=False),
    sa.Column('public_message', sa.Text(), nullable=True),
    sa.Column('internal_message', sa.Text(), nullable=True),
    sa.Column('updated_by_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_status_id'), 'system_status', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_system_status_id'), table_name='system_status')
    op.drop_table('system_status')
    # ### end Alembic commands ###
