"""add integration configs

Revision ID: e568dfcf8111
Revises: da85203567df
Create Date: 2026-07-09 15:20:28.933568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e568dfcf8111'
down_revision: Union[str, Sequence[str], None] = 'da85203567df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integration_configs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('base_url', sa.Text(), nullable=True),
    sa.Column('api_key', sa.Text(), nullable=True),
    sa.Column('api_secret', sa.Text(), nullable=True),
    sa.Column('webhook_secret', sa.Text(), nullable=True),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('last_health_status', sa.String(length=50), nullable=True),
    sa.Column('last_health_message', sa.Text(), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_configs_id'), 'integration_configs', ['id'], unique=False)
    op.create_index(op.f('ix_integration_configs_provider'), 'integration_configs', ['provider'], unique=True)
    op.create_index(op.f('ix_integration_configs_status'), 'integration_configs', ['status'], unique=False)
    op.create_table('integration_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=255), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('response_json', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integration_events_created_at'), 'integration_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_integration_events_entity_id'), 'integration_events', ['entity_id'], unique=False)
    op.create_index(op.f('ix_integration_events_entity_type'), 'integration_events', ['entity_type'], unique=False)
    op.create_index(op.f('ix_integration_events_event_type'), 'integration_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_integration_events_id'), 'integration_events', ['id'], unique=False)
    op.create_index(op.f('ix_integration_events_provider'), 'integration_events', ['provider'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integration_events_provider'), table_name='integration_events')
    op.drop_index(op.f('ix_integration_events_id'), table_name='integration_events')
    op.drop_index(op.f('ix_integration_events_event_type'), table_name='integration_events')
    op.drop_index(op.f('ix_integration_events_entity_type'), table_name='integration_events')
    op.drop_index(op.f('ix_integration_events_entity_id'), table_name='integration_events')
    op.drop_index(op.f('ix_integration_events_created_at'), table_name='integration_events')
    op.drop_table('integration_events')
    op.drop_index(op.f('ix_integration_configs_status'), table_name='integration_configs')
    op.drop_index(op.f('ix_integration_configs_provider'), table_name='integration_configs')
    op.drop_index(op.f('ix_integration_configs_id'), table_name='integration_configs')
    op.drop_table('integration_configs')
    # ### end Alembic commands ###
