"""add persistent background job queue

Revision ID: f9b3c5c6f9a2
Revises: dd65f6073acb
Create Date: 2026-07-11 13:06:15.674253

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9b3c5c6f9a2'
down_revision: Union[str, Sequence[str], None] = 'dd65f6073acb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('background_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=64), nullable=False),
    sa.Column('job_type', sa.String(length=200), nullable=False),
    sa.Column('queue_name', sa.String(length=100), nullable=False),
    sa.Column('execution_mode', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('tryon_job_id', sa.Integer(), nullable=True),
    sa.Column('external_ai_job_id', sa.Integer(), nullable=True),
    sa.Column('idempotency_key', sa.String(length=255), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.Column('error_code', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details_json', sa.Text(), nullable=True),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('progress_message', sa.String(length=500), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('max_attempts', sa.Integer(), nullable=False),
    sa.Column('retry_backoff_seconds', sa.Integer(), nullable=False),
    sa.Column('retry_backoff_multiplier', sa.Float(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(), nullable=True),
    sa.Column('available_at', sa.DateTime(), nullable=False),
    sa.Column('queued_at', sa.DateTime(), nullable=True),
    sa.Column('claimed_at', sa.DateTime(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('canceled_at', sa.DateTime(), nullable=True),
    sa.Column('cancel_requested_at', sa.DateTime(), nullable=True),
    sa.Column('last_heartbeat_at', sa.DateTime(), nullable=True),
    sa.Column('lease_owner', sa.String(length=255), nullable=True),
    sa.Column('lease_token', sa.String(length=255), nullable=True),
    sa.Column('lease_expires_at', sa.DateTime(), nullable=True),
    sa.Column('provider_job_id', sa.String(length=255), nullable=True),
    sa.Column('provider_endpoint_id', sa.String(length=255), nullable=True),
    sa.Column('worker_name', sa.String(length=255), nullable=True),
    sa.Column('worker_version', sa.String(length=100), nullable=True),
    sa.Column('is_cancelable', sa.Boolean(), nullable=False),
    sa.Column('retain_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['external_ai_job_id'], ['external_ai_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tryon_job_id'], ['tryon_jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_background_jobs_available_at'), 'background_jobs', ['available_at'], unique=False)
    op.create_index(op.f('ix_background_jobs_completed_at'), 'background_jobs', ['completed_at'], unique=False)
    op.create_index(op.f('ix_background_jobs_created_at'), 'background_jobs', ['created_at'], unique=False)
    op.create_index(op.f('ix_background_jobs_error_code'), 'background_jobs', ['error_code'], unique=False)
    op.create_index(op.f('ix_background_jobs_execution_mode'), 'background_jobs', ['execution_mode'], unique=False)
    op.create_index(op.f('ix_background_jobs_external_ai_job_id'), 'background_jobs', ['external_ai_job_id'], unique=False)
    op.create_index(op.f('ix_background_jobs_id'), 'background_jobs', ['id'], unique=False)
    op.create_index(op.f('ix_background_jobs_idempotency_key'), 'background_jobs', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_background_jobs_job_type'), 'background_jobs', ['job_type'], unique=False)
    op.create_index(op.f('ix_background_jobs_last_heartbeat_at'), 'background_jobs', ['last_heartbeat_at'], unique=False)
    op.create_index(op.f('ix_background_jobs_lease_expires_at'), 'background_jobs', ['lease_expires_at'], unique=False)
    op.create_index(op.f('ix_background_jobs_lease_owner'), 'background_jobs', ['lease_owner'], unique=False)
    op.create_index('ix_background_jobs_lease_recovery', 'background_jobs', ['status', 'lease_expires_at'], unique=False)
    op.create_index(op.f('ix_background_jobs_lease_token'), 'background_jobs', ['lease_token'], unique=False)
    op.create_index(op.f('ix_background_jobs_priority'), 'background_jobs', ['priority'], unique=False)
    op.create_index(op.f('ix_background_jobs_provider_endpoint_id'), 'background_jobs', ['provider_endpoint_id'], unique=False)
    op.create_index(op.f('ix_background_jobs_provider_job_id'), 'background_jobs', ['provider_job_id'], unique=False)
    op.create_index(op.f('ix_background_jobs_public_id'), 'background_jobs', ['public_id'], unique=True)
    op.create_index('ix_background_jobs_queue_claim', 'background_jobs', ['queue_name', 'status', 'available_at', 'priority', 'created_at'], unique=False)
    op.create_index(op.f('ix_background_jobs_queue_name'), 'background_jobs', ['queue_name'], unique=False)
    op.create_index(op.f('ix_background_jobs_retain_until'), 'background_jobs', ['retain_until'], unique=False)
    op.create_index(op.f('ix_background_jobs_scheduled_at'), 'background_jobs', ['scheduled_at'], unique=False)
    op.create_index(op.f('ix_background_jobs_status'), 'background_jobs', ['status'], unique=False)
    op.create_index(op.f('ix_background_jobs_tryon_job_id'), 'background_jobs', ['tryon_job_id'], unique=False)
    op.create_index('ix_background_jobs_user_created', 'background_jobs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_background_jobs_user_id'), 'background_jobs', ['user_id'], unique=False)
    op.create_index(op.f('ix_background_jobs_worker_name'), 'background_jobs', ['worker_name'], unique=False)
    op.create_table('background_job_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('background_job_id', sa.Integer(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('worker_name', sa.String(length=255), nullable=True),
    sa.Column('lease_token', sa.String(length=255), nullable=True),
    sa.Column('provider_job_id', sa.String(length=255), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('error_code', sa.String(length=200), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('error_details_json', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['background_job_id'], ['background_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_background_job_attempt_unique', 'background_job_attempts', ['background_job_id', 'attempt_number'], unique=True)
    op.create_index(op.f('ix_background_job_attempts_background_job_id'), 'background_job_attempts', ['background_job_id'], unique=False)
    op.create_index(op.f('ix_background_job_attempts_id'), 'background_job_attempts', ['id'], unique=False)
    op.create_index(op.f('ix_background_job_attempts_lease_token'), 'background_job_attempts', ['lease_token'], unique=False)
    op.create_index(op.f('ix_background_job_attempts_provider_job_id'), 'background_job_attempts', ['provider_job_id'], unique=False)
    op.create_index(op.f('ix_background_job_attempts_status'), 'background_job_attempts', ['status'], unique=False)
    op.create_index(op.f('ix_background_job_attempts_worker_name'), 'background_job_attempts', ['worker_name'], unique=False)
    op.create_table('background_job_dependencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('background_job_id', sa.Integer(), nullable=False),
    sa.Column('depends_on_job_id', sa.Integer(), nullable=False),
    sa.Column('dependency_type', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['background_job_id'], ['background_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['depends_on_job_id'], ['background_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_background_job_dependencies_background_job_id'), 'background_job_dependencies', ['background_job_id'], unique=False)
    op.create_index(op.f('ix_background_job_dependencies_depends_on_job_id'), 'background_job_dependencies', ['depends_on_job_id'], unique=False)
    op.create_index(op.f('ix_background_job_dependencies_id'), 'background_job_dependencies', ['id'], unique=False)
    op.create_index('ix_background_job_dependency_unique', 'background_job_dependencies', ['background_job_id', 'depends_on_job_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_background_job_dependency_unique', table_name='background_job_dependencies')
    op.drop_index(op.f('ix_background_job_dependencies_id'), table_name='background_job_dependencies')
    op.drop_index(op.f('ix_background_job_dependencies_depends_on_job_id'), table_name='background_job_dependencies')
    op.drop_index(op.f('ix_background_job_dependencies_background_job_id'), table_name='background_job_dependencies')
    op.drop_table('background_job_dependencies')
    op.drop_index(op.f('ix_background_job_attempts_worker_name'), table_name='background_job_attempts')
    op.drop_index(op.f('ix_background_job_attempts_status'), table_name='background_job_attempts')
    op.drop_index(op.f('ix_background_job_attempts_provider_job_id'), table_name='background_job_attempts')
    op.drop_index(op.f('ix_background_job_attempts_lease_token'), table_name='background_job_attempts')
    op.drop_index(op.f('ix_background_job_attempts_id'), table_name='background_job_attempts')
    op.drop_index(op.f('ix_background_job_attempts_background_job_id'), table_name='background_job_attempts')
    op.drop_index('ix_background_job_attempt_unique', table_name='background_job_attempts')
    op.drop_table('background_job_attempts')
    op.drop_index(op.f('ix_background_jobs_worker_name'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_user_id'), table_name='background_jobs')
    op.drop_index('ix_background_jobs_user_created', table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_tryon_job_id'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_status'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_scheduled_at'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_retain_until'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_queue_name'), table_name='background_jobs')
    op.drop_index('ix_background_jobs_queue_claim', table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_public_id'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_provider_job_id'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_provider_endpoint_id'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_priority'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_lease_token'), table_name='background_jobs')
    op.drop_index('ix_background_jobs_lease_recovery', table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_lease_owner'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_lease_expires_at'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_last_heartbeat_at'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_job_type'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_idempotency_key'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_id'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_external_ai_job_id'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_execution_mode'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_error_code'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_created_at'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_completed_at'), table_name='background_jobs')
    op.drop_index(op.f('ix_background_jobs_available_at'), table_name='background_jobs')
    op.drop_table('background_jobs')
    # ### end Alembic commands ###
